FROM nginx:1.25-alpine
COPY frontend-vue/dist /usr/share/nginx/html
COPY admin-vue/dist /usr/share/nginx/html/admin
COPY frontend-vue/nginx-vue.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
