-- Realistic demo data for tenant default (dealer profile, products, rebates, contracts).
DO $$
DECLARE tid uuid := '11111111-1111-1111-1111-111111111111';
BEGIN
UPDATE product_categories SET name = CASE id
  WHEN 2 THEN '介入耗材' WHEN 3 THEN '骨科植入' WHEN 4 THEN '心血管'
  WHEN 5 THEN '外科耗材' WHEN 6 THEN '手术室耗材' WHEN 7 THEN '骨科耗材'
  WHEN 8 THEN '高值耗材' ELSE name END
WHERE tenant_id = tid OR tenant_id IS NULL;
UPDATE dealers SET name='华东医械供应链有限公司', level='T1', legal_person='王磊', usc_no='91310110000017X', reg_address='上海市医药产业园1号', reg_capital=500, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='王磊', contact_phone='13810000137', contact_email='sales01@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=1;
UPDATE dealers SET name='苏州康宁医疗器械有限公司', level='T1', legal_person='李娜', usc_no='91310110000034X', reg_address='苏州市医药产业园2号', reg_capital=580, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='李娜', contact_phone='13810000274', contact_email='sales02@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=2;
UPDATE dealers SET name='杭州济民医药器械有限公司', level='T1', legal_person='张敏', usc_no='91310110000051X', reg_address='杭州市医药产业园3号', reg_capital=660, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='张敏', contact_phone='13810000411', contact_email='sales03@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=3;
UPDATE dealers SET name='南京泰和医疗科技有限公司', level='T1', legal_person='陈杰', usc_no='91310110000068X', reg_address='南京市医药产业园4号', reg_capital=740, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='陈杰', contact_phone='13810000548', contact_email='sales04@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=4;
UPDATE dealers SET name='宁波瑞康流通有限公司', level='T1', legal_person='刘洋', usc_no='91310110000085X', reg_address='宁波市医药产业园5号', reg_capital=820, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='刘洋', contact_phone='13810000685', contact_email='sales05@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=5;
UPDATE dealers SET name='合肥德医供应链有限公司', level='T1', legal_person='赵强', usc_no='91310110000102X', reg_address='合肥市医药产业园6号', reg_capital=900, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='赵强', contact_phone='13810000822', contact_email='sales06@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=6;
UPDATE dealers SET name='上海仁泽医疗器械有限公司', level='T1', legal_person='孙丽', usc_no='91310110000119X', reg_address='上海市医药产业园7号', reg_capital=980, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='孙丽', contact_phone='13810000959', contact_email='sales07@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=7;
UPDATE dealers SET name='无锡恒康医药器械有限公司', level='T1', legal_person='周斌', usc_no='91310110000136X', reg_address='无锡市医药产业园8号', reg_capital=1060, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='周斌', contact_phone='13810001096', contact_email='sales08@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=8;
UPDATE dealers SET name='常州博远医疗科技有限公司', level='T2', legal_person='王磊', usc_no='91310110000153X', reg_address='常州市医药产业园9号', reg_capital=1140, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='王磊', contact_phone='13810001233', contact_email='sales09@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=9;
UPDATE dealers SET name='徐州嘉和医疗器械有限公司', level='T2', legal_person='李娜', usc_no='91310110000170X', reg_address='徐州市医药产业园10号', reg_capital=1220, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='李娜', contact_phone='13810001370', contact_email='sales10@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=10;
UPDATE dealers SET name='山东华鲁医疗器械有限公司', level='T2', legal_person='张敏', usc_no='91310110000187X', reg_address='济南市医药产业园11号', reg_capital=1300, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='张敏', contact_phone='13810001507', contact_email='sales11@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=11;
UPDATE dealers SET name='青岛蓝海医药供应链有限公司', level='T2', legal_person='陈杰', usc_no='91310110000204X', reg_address='青岛市医药产业园12号', reg_capital=1380, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='陈杰', contact_phone='13810001644', contact_email='sales12@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=12;
UPDATE dealers SET name='烟台康泰医疗器械有限公司', level='T2', legal_person='刘洋', usc_no='91310110000221X', reg_address='烟台市医药产业园13号', reg_capital=1460, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='刘洋', contact_phone='13810001781', contact_email='sales13@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=13;
UPDATE dealers SET name='济南鲁医控股有限公司', level='T2', legal_person='赵强', usc_no='91310110000238X', reg_address='济南市医药产业园14号', reg_capital=1540, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='赵强', contact_phone='13810001918', contact_email='sales14@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=14;
UPDATE dealers SET name='潍坊明德医疗科技有限公司', level='T2', legal_person='孙丽', usc_no='91310110000255X', reg_address='潍坊市医药产业园15号', reg_capital=1620, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='孙丽', contact_phone='13810002055', contact_email='sales15@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=15;
UPDATE dealers SET name='北京京医通达有限公司', level='T2', legal_person='周斌', usc_no='91310110000272X', reg_address='北京市医药产业园16号', reg_capital=1700, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='周斌', contact_phone='13810002192', contact_email='sales16@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=16;
UPDATE dealers SET name='天津津康医疗器械有限公司', level='T2', legal_person='王磊', usc_no='91310110000289X', reg_address='天津市医药产业园17号', reg_capital=1780, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='王磊', contact_phone='13810002329', contact_email='sales17@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=17;
UPDATE dealers SET name='石家庄冀医供应链有限公司', level='T2', legal_person='李娜', usc_no='91310110000306X', reg_address='石家庄市医药产业园18号', reg_capital=1860, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='李娜', contact_phone='13810002466', contact_email='sales18@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=18;
UPDATE dealers SET name='太原晋康医疗器械有限公司', level='T2', legal_person='张敏', usc_no='91310110000323X', reg_address='太原市医药产业园19号', reg_capital=1940, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='张敏', contact_phone='13810002603', contact_email='sales19@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=19;
UPDATE dealers SET name='沈阳东北医药物流有限公司', level='T2', legal_person='陈杰', usc_no='91310110000340X', reg_address='沈阳市医药产业园20号', reg_capital=2020, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='陈杰', contact_phone='13810002740', contact_email='sales20@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=20;
UPDATE dealers SET name='大连滨海医疗器械有限公司', level='T3', legal_person='刘洋', usc_no='91310110000357X', reg_address='大连市医药产业园21号', reg_capital=2100, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='刘洋', contact_phone='13810002877', contact_email='sales21@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=21;
UPDATE dealers SET name='长春吉康医疗科技有限公司', level='T3', legal_person='赵强', usc_no='91310110000374X', reg_address='长春市医药产业园22号', reg_capital=2180, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='赵强', contact_phone='13810003014', contact_email='sales22@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=22;
UPDATE dealers SET name='哈尔滨北药流通有限公司', level='T3', legal_person='孙丽', usc_no='91310110000391X', reg_address='哈尔滨市医药产业园23号', reg_capital=2260, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='孙丽', contact_phone='13810003151', contact_email='sales23@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=23;
UPDATE dealers SET name='武汉楚医供应链有限公司', level='T3', legal_person='周斌', usc_no='91310110000408X', reg_address='武汉市医药产业园24号', reg_capital=2340, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='周斌', contact_phone='13810003288', contact_email='sales24@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=24;
UPDATE dealers SET name='长沙湘康医疗器械有限公司', level='T3', legal_person='王磊', usc_no='91310110000425X', reg_address='长沙市医药产业园25号', reg_capital=2420, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='王磊', contact_phone='13810003425', contact_email='sales25@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=25;
UPDATE dealers SET name='郑州中原医械有限公司', level='T3', legal_person='李娜', usc_no='91310110000442X', reg_address='郑州市医药产业园26号', reg_capital=2500, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='李娜', contact_phone='13810003562', contact_email='sales26@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=26;
UPDATE dealers SET name='西安秦康医疗供应链有限公司', level='T3', legal_person='张敏', usc_no='91310110000459X', reg_address='西安市医药产业园27号', reg_capital=2580, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='张敏', contact_phone='13810003699', contact_email='sales27@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=27;
UPDATE dealers SET name='成都川医智慧流通有限公司', level='T3', legal_person='陈杰', usc_no='91310110000476X', reg_address='成都市医药产业园28号', reg_capital=2660, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='陈杰', contact_phone='13810003836', contact_email='sales28@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=28;
UPDATE dealers SET name='重庆渝康医疗器械有限公司', level='T3', legal_person='刘洋', usc_no='91310110000493X', reg_address='重庆市医药产业园29号', reg_capital=2740, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='刘洋', contact_phone='13810003973', contact_email='sales29@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=29;
UPDATE dealers SET name='广州南粤医械有限公司', level='T3', legal_person='赵强', usc_no='91310110000510X', reg_address='广州市医药产业园30号', reg_capital=2820, founded_at=DATE '2018-01-01' + ((id % 48) * 30 || ' days')::interval, business_scope='医疗器械经营、第三类医疗器械销售、仓储配送、售后技术服务；医院终端开发与学术推广。', gsp_status='active', gsp_expire=DATE '2029-12-31', contact_name='赵强', contact_phone='13810004110', contact_email='sales30@demo-dms.cn', status='active', updated_at=now() WHERE tenant_id=tid AND id=30;
UPDATE products SET name_cn='一次性使用冠脉药物洗脱支架', name_en='Demo Medical Product 1', spec='标准型/无菌', unit='套', current_price=12800, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=1;
UPDATE products SET name_cn='颅内弹簧圈栓塞系统', name_en='Demo Medical Product 2', spec='加长型/无菌', unit='个', current_price=18600, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=2;
UPDATE products SET name_cn='人工髋关节假体', name_en='Demo Medical Product 3', spec='亲水涂层/6F', unit='根', current_price=9800, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=3;
UPDATE products SET name_cn='膝关节置换假体', name_en='Demo Medical Product 4', spec='70mm/无菌', unit='盒', current_price=13200, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=4;
UPDATE products SET name_cn='脊柱内固定钉棒系统', name_en='Demo Medical Product 5', spec='90mm/无菌', unit='支', current_price=7600, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=5;
UPDATE products SET name_cn='椎间融合器', name_en='Demo Medical Product 6', spec='钴铬合金/无菌', unit='件', current_price=5200, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=6;
UPDATE products SET name_cn='疝修补补片', name_en='Demo Medical Product 7', spec='钛合金/灭菌', unit='片', current_price=2680, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=7;
UPDATE products SET name_cn='超声刀头', name_en='Demo Medical Product 8', spec='55mm/灭菌', unit='把', current_price=1980, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=8;
UPDATE products SET name_cn='高频电刀笔', name_en='Demo Medical Product 9', spec='80mm/灭菌', unit='套', current_price=680, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=9;
UPDATE products SET name_cn='吻合器及钉仓', name_en='Demo Medical Product 10', spec='18mm/灭菌', unit='个', current_price=2380, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=10;
UPDATE products SET name_cn='一次性使用活检针', name_en='Demo Medical Product 11', spec='20mm/灭菌', unit='根', current_price=1280, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=11;
UPDATE products SET name_cn='中心静脉导管套件', name_en='Demo Medical Product 12', spec='150cm/6F', unit='盒', current_price=860, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=12;
UPDATE products SET name_cn='PICC导管套装', name_en='Demo Medical Product 13', spec='7Fr/20cm', unit='支', current_price=1180, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=13;
UPDATE products SET name_cn='胰岛素泵用输注器', name_en='Demo Medical Product 14', spec='4.0mm/单焦', unit='件', current_price=460, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=14;
UPDATE products SET name_cn='血液透析器', name_en='Demo Medical Product 15', spec='3.5mm/非球面', unit='片', current_price=380, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=15;
UPDATE products SET name_cn='动静脉内瘘穿刺针', name_en='Demo Medical Product 16', spec='高交联聚乙烯', unit='把', current_price=28, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=16;
UPDATE products SET name_cn='植入式心脏起搏器', name_en='Demo Medical Product 17', spec='骨水泥型', unit='套', current_price=26800, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=17;
UPDATE products SET name_cn='临时起搏电极导管', name_en='Demo Medical Product 18', spec='非骨水泥型', unit='个', current_price=1280, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=18;
UPDATE products SET name_cn='人工晶体', name_en='Demo Medical Product 19', spec='V型钉仓', unit='根', current_price=4200, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=19;
UPDATE products SET name_cn='玻璃体切割套包', name_en='Demo Medical Product 20', spec='蓝色染液/无菌', unit='盒', current_price=1860, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=20;
UPDATE products SET name_cn='骨科外固定支架', name_en='Demo Medical Product 21', spec='标准型/无菌', unit='支', current_price=3200, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=21;
UPDATE products SET name_cn='锁定加压接骨板', name_en='Demo Medical Product 22', spec='加长型/无菌', unit='件', current_price=2680, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=22;
UPDATE products SET name_cn='髓内钉系统', name_en='Demo Medical Product 23', spec='亲水涂层/6F', unit='片', current_price=3680, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=23;
UPDATE products SET name_cn='创伤钢板螺钉', name_en='Demo Medical Product 24', spec='70mm/无菌', unit='把', current_price=980, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=24;
UPDATE products SET name_cn='一次性使用切口保护套', name_en='Demo Medical Product 25', spec='90mm/无菌', unit='套', current_price=168, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=25;
UPDATE products SET name_cn='腹腔镜穿刺器', name_en='Demo Medical Product 26', spec='钴铬合金/无菌', unit='个', current_price=360, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=26;
UPDATE products SET name_cn='负压引流敷料套装', name_en='Demo Medical Product 27', spec='钛合金/灭菌', unit='根', current_price=480, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=27;
UPDATE products SET name_cn='医用透明质酸钠凝胶', name_en='Demo Medical Product 28', spec='55mm/灭菌', unit='盒', current_price=680, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=28;
UPDATE products SET name_cn='可吸收止血纱', name_en='Demo Medical Product 29', spec='80mm/灭菌', unit='支', current_price=220, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=29;
UPDATE products SET name_cn='造影导管', name_en='Demo Medical Product 30', spec='18mm/灭菌', unit='件', current_price=180, tax_rate=0.13, status='active', product_line=CASE WHEN id<=8 THEN '介入线' WHEN id<=16 THEN '外科线' WHEN id<=24 THEN '骨科线' ELSE '综合高值线' END, updated_at=now() WHERE tenant_id=tid AND id=30;
DELETE FROM rebate_previews WHERE tenant_id=tid AND dealer_id BETWEEN 1 AND 30;
INSERT INTO rebate_previews (tenant_id, dealer_id, period_yyyymm, target_amount, actual_amount, achievement_rate, tier_hit, gross_rebate, deductions, net_rebate, snapshot_at, created_at, updated_at, version)
SELECT tid, d.id, to_char(m.ym,'YYYYMM'),
  ROUND((CASE d.level WHEN 'T1' THEN 900000 WHEN 'T2' THEN 520000 ELSE 280000 END + (d.id*17000) + EXTRACT(MONTH FROM m.ym)*18000)::numeric, 2),
  ROUND((CASE d.level WHEN 'T1' THEN 900000 WHEN 'T2' THEN 520000 ELSE 280000 END + (d.id*17000) + EXTRACT(MONTH FROM m.ym)*18000) *
    (0.72 + 0.035*sin((EXTRACT(MONTH FROM m.ym)+d.id)::float/2.1) + CASE WHEN d.level='T1' THEN 0.18 WHEN d.level='T2' THEN 0.10 ELSE 0.04 END)::numeric, 2),
  0,
  jsonb_build_object('tier', CASE WHEN d.level='T1' THEN 'T3' WHEN d.level='T2' THEN 'T2' ELSE 'T1' END),
  0, '{}'::jsonb, 0, now(), now(), now(), 0
FROM dealers d CROSS JOIN generate_series(DATE '2025-01-01', DATE '2026-12-01', INTERVAL '1 month') m(ym)
WHERE d.tenant_id=tid AND d.id BETWEEN 1 AND 30;
UPDATE rebate_previews SET achievement_rate=ROUND(actual_amount/NULLIF(target_amount,0),4),
  gross_rebate=ROUND(actual_amount * CASE WHEN achievement_rate >= 1.2 THEN 0.058 WHEN achievement_rate >= 1 THEN 0.045 WHEN achievement_rate >= 0.9 THEN 0.032 ELSE 0.018 END,2),
  deductions=jsonb_build_object('reason', CASE WHEN id % 4 = 0 THEN '返利扣减' WHEN id % 4 = 1 THEN '价保扣减' WHEN id % 4 = 2 THEN '窜货扣减' ELSE '促销补差' END, 'amount', CASE WHEN id % 4 = 0 THEN ROUND(gross_rebate*0.08,2) WHEN id % 4 = 1 THEN ROUND(gross_rebate*0.05,2) WHEN id % 4 = 2 THEN ROUND(gross_rebate*0.03,2) ELSE ROUND(gross_rebate*0.02,2) END),
  net_rebate=ROUND(gross_rebate - CASE WHEN id % 4 = 0 THEN gross_rebate*0.08 WHEN id % 4 = 1 THEN gross_rebate*0.05 WHEN id % 4 = 2 THEN gross_rebate*0.03 ELSE gross_rebate*0.02 END,2),
  updated_at=now()
WHERE tenant_id=tid;
UPDATE contracts c SET
  contract_name = c.code || '-' || CASE c.category WHEN 'DISTRIBUTION' THEN '年度经销协议' WHEN 'SERVICE' THEN '售后服务协议' WHEN 'PROMOTION' THEN '市场推广协议' WHEN 'AUTHORIZATION' THEN '授权委托书' WHEN 'SUPPLY' THEN '供货框架合同' ELSE '销售合同' END || '-' || to_char(c.valid_from,'YYYY'),
  vendor_party='上海鼎医智能科技有限公司',
  dealer_party=d.name,
  sign_city=CASE WHEN d.region_id IN (7,8,15) THEN '上海' WHEN d.region_id IN (9,10,11) THEN '杭州' ELSE '北京' END,
  contract_type=CASE WHEN c.category IN ('DISTRIBUTION','SUPPLY','SALES') THEN 'FRAMEWORK' WHEN c.category='AUTHORIZATION' THEN 'AUTH' ELSE 'SERVICE' END,
  business_scope='指定医疗器械产品在授权区域内销售、配送、医院准入、学术推广及售后服务；按附件价格政策执行。',
  target_amount=ROUND((CASE c.category WHEN 'DISTRIBUTION' THEN 1800000 WHEN 'AUTHORIZATION' THEN 900000 WHEN 'PROMOTION' THEN 450000 WHEN 'SUPPLY' THEN 1200000 ELSE 360000 END + (c.id*9800))::numeric,2),
  signed_amount=ROUND((CASE c.category WHEN 'DISTRIBUTION' THEN 1800000 WHEN 'AUTHORIZATION' THEN 900000 WHEN 'PROMOTION' THEN 450000 WHEN 'SUPPLY' THEN 1200000 ELSE 360000 END + (c.id*9800)) * (0.88 + (c.id%10)::numeric/100),2),
  rebate_rate=CASE WHEN c.category IN ('DISTRIBUTION','PROMOTION') THEN 0.035 + (c.id%4)*0.005 ELSE 0 END,
  payment_terms='月结60天，凭签收单及增值税专用发票付款',
  settlement_cycle=CASE WHEN c.category='PROMOTION' THEN '季度结算' ELSE '月度对账' END,
  delivery_terms='订单确认后5个工作日内送达经销商指定三方仓库',
  owner_name='区域经理-' || LPAD(((c.id % 12)+1)::text,2,'0'),
  owner_phone='138' || LPAD(((c.id % 10000))::text,8,'0'),
  renew_before_days=60,
  updated_at=now()
FROM dealers d WHERE d.id=c.dealer_id AND c.tenant_id=tid;
END $$;
