# -*- coding: utf-8 -*-
"""Single generator for V107 orthopedic demo data. Run: python gen_all.py"""
import os, random
random.seed(20260820)
HERE=os.path.dirname(os.path.abspath(__file__))
OUT=os.path.abspath(os.path.join(HERE,"ortho_demo_data_reset.sql"))
TID="11111111-1111-1111-1111-111111111111"
L=[]
def w(s=""): L.append(s)
def q(s):
    if s is None: return "NULL"
    return "'"+str(s).replace("'","''")+"'"
def num(v): return "NULL" if v is None else str(v)

w("-- V107: Reset default-tenant business data and seed a realistic orthopedic implant dataset.")
w("-- Generated by scripts/data_reset/gen_all.py. Config tables (users/roles/permissions/menus/dicts) untouched.")
w("BEGIN;")
w(f"DO $$ DECLARE tid uuid := '{TID}'; admin_id bigint := 1; v_id bigint; BEGIN")
w("SET LOCAL session_replication_role = replica;")
w("")
w("-- unconditional cleanup of all transaction/business child tables (orphan-safe)")
for ct in ["order_lines","order_status_history","order_promotion_hits","sales_out_lines","sales_out_batches","sales_out_batch_lines","sales_out_execution_lines","purchase_order_lines","receipt_lines","receipt_batches","receipt_batch_lines","receipt_execution_lines","stock_move_lines","stocktake_lines","adjustment_lines","surgery_report_lines","promotion_rules","promotion_status_logs","loan_lines","distribution_lines","contract_revisions","contract_attachments","approval_records","approval_tasks","approval_node_assignees"]:
    w(f"DELETE FROM {ct};")
# master-child tables
for ct in ["dealer_addresses","position_dealers","sales_dealer_mapping","product_bundle_lines","product_package_levels"]:
    w(f"DELETE FROM {ct};")
w("")
w("-- ========== CLEANUP (children first) ==========")
child_dels=[("order_lines","order_id","orders"),("order_status_history","order_id","orders"),("order_promotion_hits","order_id","orders"),
 ("sales_out_lines","sales_out_id","sales_outs"),("sales_out_batches","sales_out_id","sales_outs"),("sales_out_execution_lines","sales_out_id","sales_outs"),
 ("purchase_order_lines","po_id","purchase_orders"),("receipt_lines","receipt_id","receipts"),("receipt_batches","receipt_id","receipts"),
 ("receipt_execution_lines","receipt_id","receipts"),("stock_move_lines","move_id","stock_moves"),("stocktake_lines","stocktake_id","stocktakes"),
 ("adjustment_lines","adjustment_id","inventory_adjustments"),("surgery_report_lines","report_id","surgery_reports"),
 ("promotion_rules","promotion_id","promotions"),("promotion_status_logs","promotion_id","promotions"),
 ("loan_lines","loan_id","loans"),("distribution_lines","shipment_id","distribution_shipments"),
 ("contract_revisions","contract_id","contracts"),("contract_attachments","contract_id","contracts")]
for tbl,fk,parent in child_dels:
    w(f"DELETE FROM {tbl} WHERE {fk} IN (SELECT id FROM {parent} WHERE tenant_id=tid);")
w("DELETE FROM sales_out_batch_lines WHERE batch_id IN (SELECT id FROM sales_out_batches WHERE sales_out_id IN (SELECT id FROM sales_outs WHERE tenant_id=tid));")
w("DELETE FROM receipt_batch_lines WHERE batch_id IN (SELECT id FROM receipt_batches WHERE receipt_id IN (SELECT id FROM receipts WHERE tenant_id=tid));")
for t in ["sales_out_facts","sales_invoices","purchase_invoices","erp_outbound_callbacks","approval_records","approval_tasks","approval_node_assignees","approval_instances","rma_orders","rma_authorizations","surgery_reports","loans","distribution_shipments","stock_moves","stocktakes","inventory_adjustments","promotions","rebate_previews","rebate_settlements","dealer_kpi_snapshots","authorizations","temp_authorizations","contracts","orders","sales_outs","purchase_orders","receipts","inventory","inventory_transactions","stock_serials","notifications","report_subscription","email_logs","async_task"]:
    w(f"DELETE FROM {t} WHERE tenant_id=tid;")
w("DELETE FROM product_mapping_import_batches WHERE manufacturer_tenant_id=tid;")
for t in ["dealer_addresses","position_dealers","sales_dealer_mapping","product_bundle_lines","product_bundles","product_package_levels","product_prices","price_lists","warehouses","hospitals","dealers","suppliers","products","product_categories","product_lines","regions"]:
    w(f"DELETE FROM {t} WHERE tenant_id=tid;")
seqs=["dealer_addresses_id_seq","dealers_id_seq","hospitals_id_seq","products_id_seq","product_categories_id_seq","product_lines_id_seq","product_bundles_id_seq","product_bundle_lines_id_seq","product_package_levels_id_seq","product_prices_id_seq","price_lists_id_seq","suppliers_id_seq","warehouses_id_seq","regions_id_seq","orders_id_seq","order_lines_id_seq","order_status_history_id_seq","sales_outs_id_seq","sales_out_lines_id_seq","sales_out_batches_id_seq","sales_out_batch_lines_id_seq","sales_out_execution_lines_id_seq","sales_out_facts_id_seq","sales_invoices_id_seq","purchase_orders_id_seq","purchase_order_lines_id_seq","purchase_invoices_id_seq","receipts_id_seq","receipt_lines_id_seq","receipt_batches_id_seq","receipt_batch_lines_id_seq","receipt_execution_lines_id_seq","inventory_id_seq","inventory_transactions_id_seq","stock_serials_id_seq","stock_moves_id_seq","stock_move_lines_id_seq","stocktakes_id_seq","stocktake_lines_id_seq","inventory_adjustments_id_seq","adjustment_lines_id_seq","surgery_reports_id_seq","surgery_report_lines_id_seq","promotions_id_seq","promotion_rules_id_seq","rebate_previews_id_seq","rebate_settlements_id_seq","rma_orders_id_seq","rma_authorizations_id_seq","authorizations_id_seq","temp_authorizations_id_seq","contracts_id_seq","contract_revisions_id_seq","contract_attachments_id_seq","loans_id_seq","loan_lines_id_seq","distribution_shipments_id_seq","distribution_lines_id_seq","dealer_kpi_snapshots_id_seq","notifications_id_seq","approval_instances_id_seq","approval_records_id_seq","approval_tasks_id_seq1","approval_node_assignees_id_seq","product_mapping_import_batches_id_seq","email_logs_id_seq","async_task_id_seq","report_subscription_id_seq"]
for s in seqs: w(f"PERFORM setval({q(s)},1,false);")
w("SET LOCAL session_replication_role=DEFAULT;")
w("")

# ---------- REGIONS ----------
w("-- ===== REGIONS =====")
tier1=["华东","华南","华北","西南"]
provinces={"华东":[("上海市","上海市"),("江苏省","南京市"),("浙江省","杭州市"),("安徽省","合肥市")],"华南":[("广东省","广州市"),("福建省","福州市")],"华北":[("北京市","北京市"),("天津市","天津市"),("山东省","济南市")],"西南":[("四川省","成都市"),("重庆市","重庆市")]}
cities={"上海市":["上海市"],"江苏省":["南京市","苏州市","无锡市"],"浙江省":["杭州市","宁波市"],"安徽省":["合肥市"],"广东省":["广州市","深圳市","佛山市"],"福建省":["福州市","厦门市"],"北京市":["北京市"],"天津市":["天津市"],"山东省":["济南市","青岛市"],"四川省":["成都市"],"重庆市":["重庆市"]}
rid=1; tier_ids={}; prov_ids={}; city_id_of={}
for name in tier1:
    w(f"INSERT INTO regions (id,tenant_id,code,name,parent_id,level,sort_order,status,created_at,updated_at) VALUES ({rid},tid,{q('R'+str(rid))},{q(name)},NULL,1,{rid*10},'active',now(),now());")
    tier_ids[name]=rid; rid+=1
for tier,plist in provinces.items():
    for pname,cap in plist:
        w(f"INSERT INTO regions (id,tenant_id,code,name,parent_id,level,sort_order,status,created_at,updated_at) VALUES ({rid},tid,{q('R'+str(rid))},{q(pname)},{tier_ids[tier]},2,{rid*10},'active',now(),now());")
        prov_ids[pname]=rid; rid+=1
for prov,clist in cities.items():
    for c in clist:
        w(f"INSERT INTO regions (id,tenant_id,code,name,parent_id,level,sort_order,status,created_at,updated_at) VALUES ({rid},tid,{q('R'+str(rid))},{q(c)},{prov_ids[prov]},3,{rid*10},'active',now(),now());")
        city_id_of[c]=rid; rid+=1

# ---------- PRODUCT LINES ----------
w("-- ===== PRODUCT LINES =====")
plines=[("PL-TRAUMA","创伤骨科","骨折内固定植入物及配套器械"),("PL-SPINE","脊柱外科","脊柱内固定与椎间融合系统"),("PL-JOINT","关节外科","人工髋膝关节置换假体"),("PL-SPORTS","运动医学","韧带重建与软组织修复"),("PL-BIO","生物骨科材料","骨修复与可吸收植入材料")]
pline_id={}
for i,(code,name,desc) in enumerate(plines,1):
    w(f"INSERT INTO product_lines (id,tenant_id,code,name,parent_id,level,sort_order,status,description,created_at,updated_at) VALUES ({i},tid,{q(code)},{q(name)},NULL,1,{i*10},'active',{q(desc)},now(),now());")
    pline_id[code]=i

# ---------- CATEGORIES ----------
w("-- ===== PRODUCT CATEGORIES =====")
cats=[("CAT-TRAUMA","创伤内固定",None,1),("CAT-TRAUMA-PLATE","金属接骨板",1,2),("CAT-TRAUMA-SCREW","金属接骨螺钉",1,3),("CAT-TRAUMA-NAIL","髓内钉系统",1,4),
      ("CAT-SPINE","脊柱内固定",None,5),("CAT-SPINE-PEDICLE","椎弓根螺钉系统",5,6),("CAT-SPINE-CAGE","椎间融合器",5,7),("CAT-SPINE-ROD","脊柱连接棒",5,8),
      ("CAT-JOINT","人工关节",None,9),("CAT-JOINT-HIP","髋关节假体",9,10),("CAT-JOINT-KNEE","膝关节假体",9,11),
      ("CAT-SPORTS","运动医学",None,12),("CAT-SPORTS-ANCHOR","带线锚钉",12,13),("CAT-SPORTS-BUTTON","带袢钢板",12,14),
      ("CAT-BIO","骨科生物材料",None,15),("CAT-BIO-BONE","人工骨修复材料",15,16)]
for i,(code,name,parent,sort) in enumerate(cats,1):
    pref="NULL" if parent is None else f"(SELECT id FROM product_categories WHERE code={q(cats[parent-1][0])} AND tenant_id=tid)"
    w(f"INSERT INTO product_categories (id,tenant_id,code,name,parent_id,level,sort_order,status,created_at,updated_at) VALUES ({i},tid,{q(code)},{q(name)},{pref},{1 if parent is None else 2},{sort},'active',now(),now());")

# save partial
# (collected; file written at end after document generation)
print("base collected lines:",len(L))


# ---------- SUPPLIERS ----------
w("-- ===== SUPPLIERS =====")
suppliers=[
 ("SUP-001","强生（苏州）医疗器材有限公司","周建华","13901010001","江苏省苏州市工业园区星湖街88号","91320594MA100001A"),
 ("SUP-002","美敦力医疗用品技术服务（上海）有限公司","林慧敏","13901010002","上海市浦东新区张江高科技园区博云路2号","91310115MA100002B"),
 ("SUP-003","史赛克（北京）医疗器械有限公司","吴志强","13901010003","北京市朝阳区望京东路6号","91110105MA100003C"),
 ("SUP-004","捷迈邦美医疗器械（上海）有限公司","郑雪梅","13901010004","上海市黄浦区南京西路288号","91310101MA100004D"),
 ("SUP-005","威高骨科材料股份有限公司","孙海涛","13901010005","山东省威海市旅游度假区香江街26号","91371000MA100005E"),
 ("SUP-006","大博医疗科技股份有限公司","陈丽娟","13901010006","福建省厦门市海沧区翁角西路2050号","91350200MA100006F"),
 ("SUP-007","北京春立科技科技股份有限公司","黄永刚","13901010007","北京市顺义区林河工业开发区顺仁路53号","91110113MA100007G"),
 ("SUP-008","凯利泰医疗科技股份有限公司","曹雅婷","13901010008","上海市浦东新区张江高科技园区东区","91310115MA100008H"),
]
for i,(code,name,p,phone,addr,tax) in enumerate(suppliers,1):
    w(f"INSERT INTO suppliers (id,tenant_id,code,name,contact_person,contact_phone,address,bank_account,tax_no,remark,status,level,created_at,updated_at) "
      f"VALUES ({i},tid,{q(code)},{q(name)},{q(p)},{q(phone)},{q(addr)},CONCAT('622700101',LPAD({i}::text,8,'0')),{q(tax)},'骨科植入物合格供应商','active','A',now(),now());")

# ---------- DEALERS ----------
w("-- ===== DEALERS =====")
dealers=[
 ("上海康泰医疗器械有限公司","T1","上海市","王建国","91310110MA1FLK001",1000,"2015-03-12","13800100001","wangjianguo@kangtai-med.cn","2028-06-30",2),
 ("苏州康宁医疗科技有限公司","T1","苏州市","李淑芬","91320505MA1FLK002",800,"2016-07-08","13800100002","lishufen@kangning-med.cn","2027-11-30",2),
 ("杭州济民医疗器械有限公司","T1","杭州市","张伟明","91330106MA1FLK003",750,"2017-01-20","13800100003","zhangweiming@jimin-med.cn","2029-03-15",2),
 ("南京泰和医疗器械有限公司","T2","南京市","陈晓东","91320104MA1FLK004",500,"2018-09-05","13800100004","chenxiaodong@taihe-med.cn","2028-09-20",2),
 ("宁波瑞康医疗供应链有限公司","T2","宁波市","刘芳","91330212MA1FLK005",600,"2019-04-18","13800100005","liufang@ruikang-med.cn","2027-08-10",2),
 ("合肥德医医疗器械有限公司","T2","合肥市","赵军","91340103MA1FLK006",450,"2018-11-22","13800100006","zhaojun@deyi-med.cn","2029-01-25",2),
 ("北京华诚医疗器械有限公司","T1","北京市","孙明辉","91110105MA1FLK007",1200,"2014-05-30","13800100007","sunminghui@huacheng-med.cn","2028-12-05",5),
 ("广州粤康医疗器械有限公司","T1","广州市","周琳","91440106MA1FLK008",900,"2016-02-14","13800100008","zhoulin@yuekang-med.cn","2027-10-18",3),
 ("深圳鹏瑞医疗科技有限公司","T2","深圳市","吴昊","91440305MA1FLK009",700,"2019-08-09","13800100009","wuhao@pengrui-med.cn","2029-05-22",3),
 ("成都川医医疗器械有限公司","T2","成都市","郑秀英","91510107MA1FLK010",550,"2017-06-25","13800100010","zhengxiuying@chuanyi-med.cn","2028-04-30",4),
 ("天津金邦医疗器械有限公司","T3","天津市","钱国栋","91120103MA1FLK011",300,"2020-03-11","13800100011","qianguodong@jinbang-med.cn","2027-07-14",5),
 ("青岛海诺医疗器械有限公司","T3","青岛市","冯丽","91370202MA1FLK012",350,"2020-10-08","13800100012","fengli@hainuo-med.cn","2028-11-09",5),
]
for i,(name,level,city,legal,usc,cap,founded,phone,email,gsp,pos) in enumerate(dealers,1):
    code=f"DLR-{i:03d}"
    w(f"INSERT INTO dealers (id,tenant_id,code,name,level,legal_person,usc_no,reg_address,reg_capital,founded_at,business_scope,gsp_status,gsp_expire,region_id,contact_name,contact_phone,contact_email,status,attrs,created_at,updated_at,version,sales_position_id) "
      f"VALUES ({i},tid,{q(code)},{q(name)},{q(level)},{q(legal)},{q(usc)},CONCAT({q(city)},'医药产业园',{i},'号'),{cap},DATE {q(founded)},'医疗器械经营、第三类医疗器械销售、仓储配送、医院终端开发与售后服务','active',DATE {q(gsp)},(SELECT id FROM regions WHERE name={q(city)} AND level=3 AND tenant_id=tid LIMIT 1),{q(legal)},{q(phone)},{q(email)},'active','{{}}'::jsonb,now(),now(),0,{pos});")

# ---------- DEALER ADDRESSES ----------
w("-- ===== DEALER ADDRESSES =====")
addr_cities=["上海市","苏州市","杭州市","南京市","宁波市","合肥市","北京市","广州市","深圳市","成都市","天津市","青岛市"]
aid=1
for i in range(1,13):
    city=addr_cities[i-1]
    w(f"INSERT INTO dealer_addresses (id,tenant_id,dealer_id,is_default,contact_name,phone,province,city,district,address,postal_code,created_at,updated_at) "
      f"VALUES ({aid},tid,{i},true,(SELECT contact_name FROM dealers WHERE id={i}),(SELECT contact_phone FROM dealers WHERE id={i}),{q(city)},{q(city)},'核心商务区',CONCAT('医药港路',{i*10},'号'),'200000',now(),now());")
    aid+=1
    w(f"INSERT INTO dealer_addresses (id,tenant_id,dealer_id,is_default,contact_name,phone,province,city,district,address,postal_code,created_at,updated_at) "
      f"VALUES ({aid},tid,{i},false,(SELECT contact_name FROM dealers WHERE id={i}),(SELECT contact_phone FROM dealers WHERE id={i}),{q(city)},{q(city)},'仓储区',CONCAT('物流大道',{i*20},'号三方仓'),'200000',now(),now());")
    aid+=1

# ---------- HOSPITALS ----------
w("-- ===== HOSPITALS =====")
hospitals=[
 ("上海市第六人民医院","三甲","上海市","宜山路600号","骨科采购科","021-64369181"),
 ("复旦大学附属华山医院","三甲","上海市","乌鲁木齐中路12号","设备科","021-52888001"),
 ("上海交通大学医学院附属瑞金医院","三甲","上海市","瑞金二路197号","骨科","021-64370045"),
 ("苏州大学附属第一医院","三甲","苏州市","平海路899号","采购中心","0512-67780001"),
 ("浙江大学医学院附属第二医院","三甲","杭州市","解放路88号","设备科","0571-87783777"),
 ("江苏省人民医院","三甲","南京市","广州路300号","骨科","025-83718836"),
 ("宁波市第一医院","三甲","宁波市","柳汀街59号","设备科","0574-87085588"),
 ("中国科学技术大学附属第一医院","三甲","合肥市","庐江路17号","采购科","0551-62283114"),
 ("北京积水潭医院","三甲","北京市","新街口东街31号","骨科采购科","010-58516688"),
 ("北京大学第三医院","三甲","北京市","花园北路49号","设备处","010-82266699"),
 ("广州医科大学附属第三医院","三甲","广州市","多宝路63号","骨科","020-81292183"),
 ("深圳市第二人民医院","三甲","深圳市","笋岗西路3002号","设备科","0755-83366388"),
 ("四川大学华西医院","三甲","成都市","国学巷37号","骨科采购部","028-85422114"),
 ("天津医院","三甲","天津市","解放南路406号","设备科","022-28332713"),
 ("山东大学齐鲁医院","三甲","济南市","文化西路107号","骨科","0531-82166666"),
 ("厦门大学附属第一医院","三甲","厦门市","上古街10号","设备科","0592-2137710"),
]
for i,(name,level,city,addr,contact,phone) in enumerate(hospitals,1):
    w(f"INSERT INTO hospitals (id,tenant_id,code,name,type,level,region_id,address,contact,phone,status,created_at,updated_at) "
      f"VALUES ({i},tid,{q('HOS-'+f'{i:03d}')},{q(name)},'综合医院',{q(level)},(SELECT id FROM regions WHERE name={q(city)} AND level=3 AND tenant_id=tid LIMIT 1),{q(addr)},{q(contact)},{q(phone)},'active',now(),now());")

# ---------- WAREHOUSES ----------
w("-- ===== WAREHOUSES =====")
wid=1
for i in range(1,13):
    w(f"INSERT INTO warehouses (id,tenant_id,dealer_id,code,name,type,hospital_id,address,status,created_at,updated_at) "
      f"VALUES ({wid},tid,{i},CONCAT('WH-D',LPAD({i}::text,3,'0')),CONCAT((SELECT name FROM dealers WHERE id={i}),'中心仓'),'DEALER',NULL,CONCAT('仓储区物流大道',{i*20},'号'),'active',now(),now());")
    wid+=1
for i in range(1,11):
    w(f"INSERT INTO warehouses (id,tenant_id,dealer_id,code,name,type,hospital_id,address,status,created_at,updated_at) "
      f"VALUES ({wid},tid,{i},CONCAT('WH-H',LPAD({i}::text,3,'0')),CONCAT((SELECT name FROM hospitals WHERE id={i}),'寄售库'),'HOSPITAL',{i},(SELECT address FROM hospitals WHERE id={i}),'active',now(),now());")
    wid+=1

# ---------- POSITION DEALERS + SALES DEALER MAPPING ----------
w("-- ===== POSITION_DEALERS / SALES_DEALER_MAPPING =====")
for i in range(1,13):
    pos = [2,2,2,2,2,2,5,3,3,4,5,5][i-1]
    su  = [6,7,7,7,7,7,12,8,9,10,12,12][i-1]
    w(f"INSERT INTO position_dealers (tenant_id,position_id,dealer_id,created_at) VALUES (tid,{pos},{i},now());")
    w(f"INSERT INTO sales_dealer_mapping (tenant_id,sales_user_id,dealer_id,since_date,created_at) VALUES (tid,{su},{i},DATE '2025-01-01',now());")


# ---------- PRODUCTS ----------
w("-- ===== PRODUCTS =====")
# (code, name, line_code, cat_code, spec, unit, price, cost, serial, safety)
products=[
 # 创伤
 ("PRD-T001","金属锁定接骨板（胫骨近端外侧）","PL-TRAUMA","CAT-TRAUMA-PLATE","3孔/左/钛合金","块",2800,1680,True,5),
 ("PRD-T002","金属锁定接骨板（股骨远端外侧）","PL-TRAUMA","CAT-TRAUMA-PLATE","5孔/右/钛合金","块",3200,1920,True,5),
 ("PRD-T003","锁定接骨螺钉（皮质骨）","PL-TRAUMA","CAT-TRAUMA-SCREW","φ3.5×40mm/钛合金","枚",180,96,False,30),
 ("PRD-T004","锁定接骨螺钉（松质骨）","PL-TRAUMA","CAT-TRAUMA-SCREW","φ4.0×50mm/钛合金","枚",220,118,False,30),
 ("PRD-T005","股骨髓内钉系统","PL-TRAUMA","CAT-TRAUMA-NAIL","直径10mm/长度340mm/钛合金","套",6800,4080,True,3),
 ("PRD-T006","胫骨髓内钉系统","PL-TRAUMA","CAT-TRAUMA-NAIL","直径9mm/长度300mm/钛合金","套",6200,3720,True,3),
 # 脊柱
 ("PRD-S001","脊柱椎弓根螺钉（万向）","PL-SPINE","CAT-SPINE-PEDICLE","φ5.5×45mm/钛合金","枚",480,288,False,20),
 ("PRD-S002","脊柱椎弓根螺钉（单轴）","PL-SPINE","CAT-SPINE-PEDICLE","φ6.0×50mm/钛合金","枚",450,270,False,20),
 ("PRD-S003","椎间融合器（TLIF）","PL-SPINE","CAT-SPINE-CAGE","9×26×10mm/PEEK","个",2600,1560,True,5),
 ("PRD-S004","椎间融合器（OLIF）","PL-SPINE","CAT-SPINE-CAGE","12×50×10mm/PEEK","个",3000,1800,True,5),
 ("PRD-S005","脊柱连接棒","PL-SPINE","CAT-SPINE-ROD","φ5.5×150mm/钛合金","根",260,156,False,20),
 # 关节
 ("PRD-J001","生物型髋关节假体（髋臼杯）","PL-JOINT","CAT-JOINT-HIP","φ52mm/钛合金涂层","个",4800,2880,True,3),
 ("PRD-J002","生物型髋关节假体（股骨柄）","PL-JOINT","CAT-JOINT-HIP","3号/钛合金涂层","个",5200,3120,True,3),
 ("PRD-J003","髋关节球头（陶瓷）","PL-JOINT","CAT-JOINT-HIP","φ28mm/陶瓷","个",2200,1320,True,5),
 ("PRD-J004","髋关节内衬（高交联聚乙烯）","PL-JOINT","CAT-JOINT-HIP","φ28mm/高交联PE","个",980,588,False,8),
 ("PRD-J005","全膝关节假体（股骨部件）","PL-JOINT","CAT-JOINT-KNEE","3号/钴铬钼合金","个",5600,3360,True,3),
 ("PRD-J006","全膝关节假体（胫骨托）","PL-JOINT","CAT-JOINT-KNEE","3号/钛合金","个",4600,2760,True,3),
 ("PRD-J007","膝关节垫片（高交联聚乙烯）","PL-JOINT","CAT-JOINT-KNEE","3号/9mm/高交联PE","个",1200,720,False,6),
 # 运动医学
 ("PRD-M001","带线锚钉（PEEK）","PL-SPORTS","CAT-SPORTS-ANCHOR","φ3.5mm/双针带线","枚",680,408,False,15),
 ("PRD-M002","带线锚钉（可吸收）","PL-SPORTS","CAT-SPORTS-ANCHOR","φ3.0mm/PLGA可吸收","枚",880,528,False,15),
 ("PRD-M003","带袢钢板（Endobutton）","PL-SPORTS","CAT-SPORTS-BUTTON","钛合金/连续袢","个",520,312,False,15),
 # 生物材料
 ("PRD-B001","人工骨修复颗粒（β-TCP）","PL-BIO","CAT-BIO-BONE","1g/瓶","瓶",360,216,False,20),
 ("PRD-B002","可吸收止血骨蜡","PL-BIO","CAT-BIO-BONE","2.5g/盒","盒",120,72,False,30),
 ("PRD-B003","医用透明质酸钠凝胶（关节腔）","PL-BIO","CAT-BIO-BONE","2.5ml/支","支",280,168,False,20),
 # BOM 套装母件（v4.1：母件无实物、零金额，价格由子件汇总）
 ("BOM-HIP-01","生物型全髋关节假体套装","PL-JOINT","CAT-JOINT-HIP","含髋臼杯/股骨柄/球头/内衬","套",13180,0,False,3),
 ("BOM-KNEE-01","全膝关节表面置换套装","PL-JOINT","CAT-JOINT-KNEE","含股骨部件/胫骨托/垫片","套",11400,0,False,3),
 ("BOM-NAIL-01","股骨髓内钉手术套装","PL-TRAUMA","CAT-TRAUMA-NAIL","含主钉/锁钉/ cap","套",7840,0,False,3),
]
BOM_PARENT_CODES = {"BOM-HIP-01","BOM-KNEE-01","BOM-NAIL-01"}
prod_id_of={}
for i,(code,name,line_code,cat_code,spec,unit,price,cost,serial,safety) in enumerate(products,1):
    prod_id_of[code]=i
    is_bom = "true" if code in BOM_PARENT_CODES else "false"
    ptype = "IMPLANT"  # all orthopedic SKUs (including BOM bundle parents) are implants; is_bundle flag distinguishes sets
    w(f"INSERT INTO products (id,tenant_id,code,name_cn,name_en,category_id,spec,unit,current_price,tax_rate,udi_required,warn_months,safety_qty,min_order_qty,status,product_line,product_line_id,is_serial_managed,unit_type,base_unit,is_bundle,product_type,created_at,updated_at,version) "
      f"VALUES ({i},tid,{q(code)},{q(name)},NULL,(SELECT id FROM product_categories WHERE code={q(cat_code)} AND tenant_id=tid),{q(spec)},{q(unit)},{price},0.13,true,6,{safety},1,'active',{q(line_code)},{pline_id[line_code]},{str(serial).lower()},'EA',{q(unit)},{is_bom},'{ptype}',now(),now(),0);")

# ---------- PRODUCT PACKAGE LEVELS (each product: 盒->个) ----------
w("-- ===== PRODUCT PACKAGE LEVELS =====")
pl_id=1
for i in range(1,len(products)+1):
    serial = products[i-1][8]
    w(f"INSERT INTO product_package_levels (id,tenant_id,product_id,parent_id,level,code,name,quantity,uom,gtin,sn_rule,status,sort_order,created_at,updated_at) "
      f"VALUES ({pl_id},tid,{i},NULL,1,CONCAT('PKG-',{i},'-BOX'),'包装盒',1,'box',CONCAT('069',LPAD({i}::text,10,'0')),NULL,'active',1,now(),now());")
    pl_id+=1
    if serial:
        w(f"INSERT INTO product_package_levels (id,tenant_id,product_id,parent_id,level,code,name,quantity,uom,gtin,sn_rule,status,sort_order,created_at,updated_at) "
          f"VALUES ({pl_id},tid,{i},{pl_id-1},2,CONCAT('PKG-',{i},'-EA'),'单品',1,'piece',NULL,'SN', 'active',2,now(),now());")
        pl_id+=1

# ---------- PRODUCT PRICES ----------
w("-- ===== PRODUCT PRICES (global standalone sale prices, v4.1) =====")
for i,(code,name,line_code,cat_code,spec,unit,price,cost,serial,safety) in enumerate(products,1):
    if code in BOM_PARENT_CODES:
        # BOM 母件不维护单品价；价格由 BOM_HEADER(0) + BOM_COMPONENT(子件) 表达
        continue
    w(f"INSERT INTO product_prices (tenant_id,product_id,partner_type,partner_id,purchase_price,sales_price,currency,effective_date,expire_date,remark,status,price_scope,purchase_price_excl_tax,sales_price_excl_tax,tax_rate,valid_from,valid_to,price_context,bom_parent_product_id,created_at,updated_at) "
      f"VALUES (tid,{i},'GLOBAL',0,{cost},{price},'CNY',DATE '2026-01-01',DATE '2026-12-31','全国统一指导价','active','SALE',ROUND({cost}/1.13,2),ROUND({price}/1.13,2),0.13,now(),DATE '2026-12-31 23:59:59+08','STANDALONE',NULL,now(),now());")

# ---------- BOM PRICES (header 0 + component prices) ----------
w("-- ===== BOM PRICES (BOM_HEADER zero + BOM_COMPONENT per child, v4.1) =====")
# (parent_code, [(child_code, price), ...])
bom_pricing = [
    ("BOM-HIP-01", [("PRD-J001",4800),("PRD-J002",5200),("PRD-J003",2200),("PRD-J004",980)]),
    ("BOM-KNEE-01", [("PRD-J005",5600),("PRD-J006",4600),("PRD-J007",1200)]),
    ("BOM-NAIL-01", [("PRD-T005",6800),("PRD-T003",180),("PRD-T004",220)]),
]
for parent_code, children in bom_pricing:
    pid = prod_id_of[parent_code]
    # BOM_HEADER 0 元头记录
    w(f"INSERT INTO product_prices (tenant_id,product_id,partner_type,partner_id,purchase_price,sales_price,currency,effective_date,expire_date,remark,status,price_scope,purchase_price_excl_tax,sales_price_excl_tax,tax_rate,valid_from,valid_to,price_context,bom_parent_product_id,created_at,updated_at) "
      f"VALUES (tid,{pid},'DEALER',0,0,0,'CNY',NULL,NULL,'BOM 母件价（子件汇总）','active','SALE',0,0,0.13,now(),DATE '2026-12-31 23:59:59+08','BOM_HEADER',NULL,now(),now());")
    for child_code, cprice in children:
        cid = prod_id_of[child_code]
        ccost = round(cprice*0.6,2)
        w(f"INSERT INTO product_prices (tenant_id,product_id,partner_type,partner_id,purchase_price,sales_price,currency,effective_date,expire_date,remark,status,price_scope,purchase_price_excl_tax,sales_price_excl_tax,tax_rate,valid_from,valid_to,price_context,bom_parent_product_id,created_at,updated_at) "
          f"VALUES (tid,{cid},'DEALER',0,{ccost},{cprice},'CNY',NULL,NULL,'BOM 子件价','active','SALE',ROUND({ccost}/1.13,2),ROUND({cprice}/1.13,2),0.13,now(),DATE '2026-12-31 23:59:59+08','BOM_COMPONENT',{pid},now(),now());")

# ---------- PRICE LISTS (dealer-specific tier pricing for first 6 dealers) ----------
w("-- ===== PRICE LISTS (dealer contracts) =====")
for i,(code,name,line_code,cat_code,spec,unit,price,cost,serial,safety) in enumerate(products,1):
    for d in range(1,7):
        tier_price = round(price*[0.92,0.94,0.95,0.96,0.965,0.97][d-1],2)
        w(f"INSERT INTO price_lists (tenant_id,product_id,dealer_id,price,currency,valid_from,valid_to,source,created_at,updated_at) "
          f"VALUES (tid,{i},{d},{tier_price},'CNY',DATE '2026-01-01',DATE '2026-12-31','CONTRACT',now(),now());")

# ---------- PRODUCT BUNDLES (hip/knee set) ----------
w("-- ===== PRODUCT BUNDLES =====")
# bundle 1: 髋关节假体套装 = cup + stem + head + liner
# bundle 2: 膝关节假体套装 = femoral + tibial + insert
bundles=[
 ("BOM-HIP-01","BDL-HIP-SET","生物型全髋关节假体套装",[("PRD-J001",1),("PRD-J002",1),("PRD-J003",1),("PRD-J004",1)]),
 ("BOM-KNEE-01","BDL-KNEE-SET","全膝关节表面置换套装",[("PRD-J005",1),("PRD-J006",1),("PRD-J007",1)]),
 ("BOM-NAIL-01","BDL-NAIL-FEM","股骨髓内钉手术套装",[("PRD-T005",1),("PRD-T003",4),("PRD-T004",2)]),
]
bid=1; blid=1
for parent_code,bcode,bname,comps in bundles:
    anchor=prod_id_of[parent_code]
    w(f"INSERT INTO product_bundles (id,tenant_id,product_id,code,name,description,pricing_type,bundle_price,allow_split,split_rule,status,bom_version,version_status,created_at,updated_at) "
      f"VALUES ({bid},tid,{anchor},{q(bcode)},{q(bname)},'成套手术器械组合，按套计价','COMPONENT',NULL,false,NULL,'active','1.0','active',now(),now());")
    for seq,(ccode,qty) in enumerate(comps,1):
        w(f"INSERT INTO product_bundle_lines (id,tenant_id,bundle_id,child_product_id,line_type,quantity,is_required,sort_order,description,status,created_at,updated_at) "
          f"VALUES ({blid},tid,{bid},{prod_id_of[ccode]},'FIXED',{qty},true,{seq},(SELECT name_cn FROM products WHERE id={prod_id_of[ccode]}),'active',now(),now());")
        blid+=1
    bid+=1

w("")
w("RAISE NOTICE 'master data done';")


# =========================================================================
# 3. DOCUMENT DATA - deterministic simulation
# =========================================================================
import datetime as dt
w("")
w("-- ========== PURCHASE ORDERS / RECEIPTS / INVENTORY ==========")

# Build product lookup
PROD={}
for i,(code,name,line_code,cat_code,spec,unit,price,cost,serial,safety) in enumerate(products,1):
    PROD[i]={"code":code,"name":name,"spec":spec,"unit":unit,"price":price,"cost":cost,"serial":serial,"tax":0.13}

# inventory state: key (dealer,wh,product,batch,status,prod_date,exp_date) -> qty
INV={}
# serial registry for serial-managed products: list of (serial, dealer, wh, batch, prod_date, exp_date)
SERIALS=[]

def add_inv(dealer,wh,pid,batch,qty,prod,exp,status="QUALIFIED"):
    if qty<=0: return
    if not PROD[pid]["serial"]:
        k=(dealer,wh,pid,batch,status,prod,exp)
        INV[k]=INV.get(k,0)+qty
    else:
        # serial-managed: create individual serial rows
        base="SN"+PROD[pid]["code"].replace("PRD-","")+"-"+batch[-4:]
        for j in range(int(qty)):
            sn=f"{base}-{len(SERIALS)+1:05d}"
            SERIALS.append((sn,dealer,wh,pid,batch,status,prod,exp))

def consume_serials(dealer,wh,pid,qty):
    out=[]
    remaining=int(qty)
    for s in list(SERIALS):
        if remaining<=0: break
        sn,d,w,pid2,batch,status,prod,exp=s
        if d==dealer and w==wh and pid2==pid and status=="QUALIFIED":
            out.append((sn,batch,prod,exp)); SERIALS.remove(s)
            remaining-=1
    return out

def dealer_stock_units(dealer,wh,pid):
    units=sum(v for k,v in INV.items() if k[0]==dealer and k[1]==wh and k[2]==pid and k[4]=='QUALIFIED' and v>0)
    units += sum(1 for s in SERIALS if s[1]==dealer and s[2]==wh and s[3]==pid and s[4]=='QUALIFIED')
    return int(units)

def consume_batch(dealer,wh,pid,qty):
    """FIFO by exp_date; returns list of (batch,prod,exp,used_qty,serials) and leftover qty."""
    used=[]; remaining=int(qty)
    cand=sorted([(k,v) for k,v in INV.items() if k[0]==dealer and k[1]==wh and k[2]==pid and k[4]=="QUALIFIED" and v>0], key=lambda x:(x[0][6], x[0][3]))
    for (d,w,p,batch,status,prod,exp),avail in cand:
        if remaining<=0: break
        take=min(avail,remaining)
        used.append((batch,prod,exp,take,[]))
        INV[(d,w,p,batch,status,prod,exp)]-=take
        remaining-=take
    # if not enough batch-managed stock, try serials
    serials_used=[]
    if remaining>0:
        su=consume_serials(dealer,wh,pid,remaining)
        if su:
            serials_used=su
            remaining-=len(su)
    return used, serials_used, remaining

po_id=1; pol_id=1; rec_id=1; recl_id=1; recb_id=1; recbl_id=1; recex_id=1
inv_id=1; itxn_id=1; serial_db_id=1
po_counters={}

def docno(prefix,d):
    ym=d.strftime("%Y%m")
    key=(prefix,ym)
    po_counters[key]=po_counters.get(key,0)+1
    return f"{prefix}-{ym}-{po_counters[key]:04d}"

# Distribute products to suppliers by line
def supplier_for(pid):
    code=PROD[pid]["code"]
    if code.startswith("PRD-T"): return 1  # 强生 trauma
    if code.startswith("PRD-S"): return 2  # 美敦力 spine
    if code.startswith("PRD-J"): return 4  # 捷迈 joint
    if code.startswith("PRD-M"): return 6  # 大博 sports
    return 5  # 威高 bio

# --- PURCHASE ORDERS + RECEIPTS (Jun 1 - Jul 20 2026) ---
start=dt.date(2026,7,1)
po_dates=[start+dt.timedelta(days=k) for k in range(20)]
po_records=[]
for d in po_dates:
    for dealer_id in range(1,13):
        wh=dealer_id  # main warehouse id == dealer id (1..12)
        nlines=random.choice([1,2,3])
        chosen=random.sample(range(1,25),nlines)
        code=docno("PO",d)
        total=0; tax_total=0
        line_rows=[]
        for seq,pid in enumerate(chosen,1):
            qty=random.choice([30,50,60,80,100,120]) if not PROD[pid]["serial"] else random.choice([8,12,15,20,25,30])
            up=PROD[pid]["cost"]
            sub=round(up*qty,2)
            tax=round(sub*PROD[pid]["tax"]/(1+PROD[pid]["tax"]),2)
            total+=sub; tax_total+=tax
            line_rows.append((seq,pid,qty,up,sub,tax))
        total=round(total,2); tax_total=round(tax_total,2)
        w(f"INSERT INTO purchase_orders (id,tenant_id,code,order_type,supplier_id,supplier_name,warehouse_id,amount_incl_tax,discount_amount,final_amount,tax_amount,expected_date,status,remark,submitted_at,approved_at,approved_by,completed_at,created_at,updated_at,created_by,is_red,audit_user_id,audit_user_name,audit_time) "
          f"VALUES ({po_id},tid,{q(code)},'NORMAL',{supplier_for(pid)},(SELECT name FROM suppliers WHERE id={supplier_for(pid)}),{wh},{total},0,{total},{tax_total},DATE {q(d.isoformat())},'COMPLETED','常规补货订单',TIMESTAMP {q(d.isoformat()+' 09:00:00+08')},TIMESTAMP {q(d.isoformat()+' 10:30:00+08')},admin_id,TIMESTAMP {q((d+dt.timedelta(days=1)).isoformat()+' 14:00:00+08')},now(),now(),admin_id,false,admin_id,'系统管理员',now());")
        for seq,pid,qty,up,sub,tax in line_rows:
            w(f"INSERT INTO purchase_order_lines (id,po_id,seq,product_id,qty,received_qty,unit_price,tax_rate,subtotal,remark,created_at) "
              f"VALUES ({pol_id},{po_id},{seq},{pid},{qty},{qty},{up},{PROD[pid]['tax']},{sub},'常规采购',now());")
            pol_id+=1
        # receipt 1 day later, complete
        recv_d=d
        rcode=docno("GR",recv_d)
        w(f"INSERT INTO receipts (id,tenant_id,code,receipt_type,ref_doc_type,ref_doc_id,dealer_id,warehouse_id,status,received_at,received_by,remark,created_at,updated_at,created_by,is_red,auto_created,source_po_id) "
          f"VALUES ({rec_id},tid,{q(rcode)},'PURCHASE','PURCHASE_ORDER',{po_id},{dealer_id},{wh},'CONFIRMED',TIMESTAMP {q(recv_d.isoformat()+' 08:30:00+08')},admin_id,'采购入库确认',now(),now(),admin_id,false,true,{po_id});")
        # one batch header per receipt
        w(f"INSERT INTO receipt_batches (id,tenant_id,receipt_id,code,seq,status,remark,confirmed_at,confirmed_by,created_at,updated_at,created_by) "
          f"VALUES ({recb_id},tid,{rec_id},CONCAT('GRB-',{rec_id},'-01'),1,'CONFIRMED','整批收货',TIMESTAMP {q(recv_d.isoformat()+' 08:30:00+08')},admin_id,now(),now(),admin_id);")
        for seq,pid,qty,up,sub,tax in line_rows:
            batch=f"B{recv_d.strftime('%y%m%d')}{pid:03d}{rec_id:03d}"
            prod_d=recv_d-dt.timedelta(days=random.choice([30,60,90]))
            exp_d=prod_d+dt.timedelta(days=365*3)
            w(f"INSERT INTO receipt_lines (id,receipt_id,product_id,batch_no,prod_date,exp_date,expected_qty,received_qty,cancelled_qty,created_at) "
              f"VALUES ({recl_id},{rec_id},{pid},{q(batch)},DATE {q(prod_d.isoformat())},DATE {q(exp_d.isoformat())},{qty},{qty},0,now());")
            sn_text=None
            if PROD[pid]["serial"]:
                serials=[]
                for _ in range(int(qty)):
                    sn=f"SN{PROD[pid]['code'].replace('PRD-','')}-{batch[-4:]}-{len(SERIALS)+1:05d}"
                    serials.append(sn)
                    SERIALS.append((sn,dealer_id,wh,pid,batch,"QUALIFIED",prod_d,exp_d))
                sn_text=",".join(serials)
            w(f"INSERT INTO receipt_batch_lines (id,batch_id,po_line_seq,receipt_line_no,product_id,qty,batch_no,serial_nos,remark,created_at) "
              f"VALUES ({recbl_id},{recb_id},{seq},{seq},{pid},{qty},{q(batch)},{q(sn_text)},'按批收货',now());")
            w(f"INSERT INTO receipt_execution_lines (id,tenant_id,receipt_id,receipt_line_id,product_id,batch_no,qty,seq_no,operator_id,created_at) "
              f"VALUES ({recex_id},tid,{rec_id},{recl_id},{pid},{q(batch)},{qty},{seq},admin_id,now());")
            if not PROD[pid]["serial"]:
                add_inv(dealer_id,wh,pid,batch,qty,prod_d,exp_d,"QUALIFIED")
            w(f"INSERT INTO inventory_transactions (id,tenant_id,dealer_id,warehouse_id,product_id,batch_no,qty_change,txn_type,ref_doc_type,ref_doc_id,at_time,operator_id) "
              f"VALUES ({itxn_id},tid,{dealer_id},{wh},{pid},{q(batch)},{qty},'PURCHASE_IN','RECEIPT',{rec_id},TIMESTAMP {q(recv_d.isoformat()+' 08:30:00+08')},admin_id);")
            itxn_id+=1
            recl_id+=1; recbl_id+=1; recex_id+=1
        rec_id+=1; recb_id+=1
        po_records.append((po_id,dealer_id,wh,line_rows,d))
        po_id+=1

po_records.sort(key=lambda r: r[4])  # tuple: po_id, dealer, wh, lines, po_date
print("POs generated:",len(po_records),"inventory batch rows:",len(INV),"serial units:",len(SERIALS))


w("")
w("-- ========== SALES ORDERS + SALES OUTS ==========")
so_id=1; sol_id=1; sohist_id=1
sout_id=1; soutl_id=1; soutb_id=1; soutbl_id=1; soute_id=1
soutfact_id=1; sinv_id=1
so_counters={}
def docno_s(prefix,d):
    ym=d.strftime("%Y%m")
    so_counters[(prefix,ym)]=so_counters.get((prefix,ym),0)+1
    return f"{prefix}-{ym}-{so_counters[(prefix,ym)]:04d}"

# Sales orders over 2026-07-01 .. 2026-08-19, varied statuses
so_start=dt.date(2026,7,1); so_end=dt.date(2026,8,19)
so_days=[so_start+dt.timedelta(days=k) for k in range((so_end-so_start).days+1)]

# map dealers to hospitals they serve
dealer_hospitals={1:[1,2,3],2:[4,5],3:[5,6],4:[6],5:[7],6:[8],7:[9,10],8:[11,12],9:[12],10:[13],11:[14],12:[15,16]}

order_statuses_cycle=["SUBMITTED","APPROVED","COMPLETED"]
sales_orders=[]  # (so_id, dealer, wh, lines, order_date, status, hospital)
for d in so_days:
    # ~3 orders per day
    for _ in range(3):
        dealer_id=random.choice(range(1,13))
        wh=dealer_id
        hosp=random.choice(dealer_hospitals.get(dealer_id,[1]))
        hosp_wh=12+hosp  # hospital consignment warehouse id (13..22)
        code=docno_s("SO",d)
        # determine status: older orders more likely completed
        age=(so_end-d).days
        if age>20: status="COMPLETED"
        elif age>8: status=random.choice(["APPROVED","COMPLETED","COMPLETED"])
        else: status=random.choice(["SUBMITTED","APPROVED","COMPLETED"])
        order_lines=[]; total=0; tax_total=0; am_ext=0
        candidate_products=random.sample(range(1,25), random.choice([1,1,2,3]))
        for seq,pid in enumerate(candidate_products,1):
            if dealer_id<=6:
                up=round(PROD[pid]["price"]*[0.92,0.94,0.95,0.96,0.965,0.97][dealer_id-1],2)
            else:
                up=PROD[pid]["price"]
            qty=random.choice([1,2,3,5]) if PROD[pid]["serial"] else random.choice([5,10,20,30,50])
            sub=round(up*qty,2)
            ext=round(sub/1.13,2); tax=round(sub-ext,2)
            total+=sub; tax_total+=tax; am_ext+=ext
            order_lines.append([seq,pid,qty,up,sub,ext,tax])
        if not order_lines:
            continue
        total=round(total,2); tax_total=round(tax_total,2); am_ext=round(am_ext,2)
        ship_addr=((dealer_id-1)*2+1)  # first address id of dealer (default)
        exp=d+dt.timedelta(days=3)
        # timestamps
        submitted=dt.datetime.combine(d,dt.time(9,random.randint(0,59)))
        approved=submitted+dt.timedelta(hours=random.randint(1,8)) if status!="SUBMITTED" else None
        completed=approved+dt.timedelta(days=random.randint(1,3)) if status=="COMPLETED" else None
        w(f"INSERT INTO orders (id,tenant_id,code,order_type,dealer_id,ship_address_id,status,amount_incl_tax,discount_amount,final_amount,tax_amount,amount_excl_tax,remark,expected_date,submitted_at,approved_at,approved_by,completed_at,created_at,updated_at,created_by,version,is_red,erp_status,warehouse_id,header_discount_type,header_discount_value) "
          f"VALUES ({so_id},tid,{q(code)},'STANDARD',{dealer_id},{ship_addr},{q(status)},{total},0,{total},{tax_total},{am_ext},'常规销售订单',DATE {q(exp.isoformat())},"
          f"TIMESTAMP {q(submitted.isoformat()+'+08')},"
          f"{('TIMESTAMP '+q(approved.isoformat()+'+08')) if approved else 'NULL'},"
          f"{'admin_id' if approved else 'NULL'},"
          f"{('TIMESTAMP '+q(completed.isoformat()+'+08')) if completed else 'NULL'},"
          f"now(),now(),admin_id,0,false,'NOT_REQUIRED',{wh},'NONE',0);")
        for seq,pid,qty,up,sub,ext,tax in order_lines:
            w(f"INSERT INTO order_lines (id,order_id,product_id,qty,unit_price,tax_rate,sub_total,is_gift,seq,product_code,product_name,product_spec,standard_price_incl_tax,line_discount_type,line_discount_value,promo_discount_amount,header_discount_amount,discount_amount,final_amount,amount_excl_tax,tax_amount,closed_qty,bom_parent_product_id,component_qty,line_discount_amount,is_group_header,created_at,updated_at) "
              f"VALUES ({sol_id},{so_id},{pid},{qty},{up},{PROD[pid]['tax']},{sub},false,{seq},(SELECT code FROM products WHERE id={pid}),(SELECT name_cn FROM products WHERE id={pid}),(SELECT spec FROM products WHERE id={pid}),{PROD[pid]['price']},'NONE',0,0,0,0,{sub},{ext},{tax},{qty if status=='COMPLETED' else 0},NULL,1,0,false,now(),now());")
            sol_id+=1
        w(f"INSERT INTO order_status_history (id,order_id,from_status,to_status,action,operator_id,comment,at_time) "
          f"VALUES ({sohist_id},{so_id},'DRAFT','SUBMITTED','SUBMIT',admin_id,'提交订单',TIMESTAMP {q(submitted.isoformat()+'+08')});")
        sohist_id+=1
        if approved:
            w(f"INSERT INTO order_status_history (id,order_id,from_status,to_status,action,operator_id,comment,at_time) "
              f"VALUES ({sohist_id},{so_id},'SUBMITTED','APPROVED','APPROVE',admin_id,'审批通过',TIMESTAMP {q(approved.isoformat()+'+08')});")
            sohist_id+=1
        if completed:
            w(f"INSERT INTO order_status_history (id,order_id,from_status,to_status,action,operator_id,comment,at_time) "
              f"VALUES ({sohist_id},{so_id},'APPROVED','COMPLETED','COMPLETE',admin_id,'订单完成',TIMESTAMP {q(completed.isoformat()+'+08')});")
            sohist_id+=1
        sales_orders.append([so_id,dealer_id,wh,hosp,hosp_wh,order_lines,d,status,approved,completed])
        so_id+=1

# For COMPLETED orders, generate sales out (delivery) and consume inventory
sales_orders.sort(key=lambda r: (r[6], r[0]))
w("")
w("-- sales out deliveries for completed orders")
for (oid,dealer_id,wh,hosp,hosp_wh,order_lines,d,status,approved,completed) in sales_orders:
    if status!="COMPLETED": continue
    ship_d=(completed or approved or d)
    ship_date=ship_d.date() if isinstance(ship_d,dt.datetime) else ship_d
    feasible=True; planned=[]; inv_snapshot=INV.copy(); serials_snapshot=list(SERIALS)
    for seq,pid,qty,up,sub,ext,tax in order_lines:
        used,serials,short=consume_batch(dealer_id,wh,pid,qty)
        if short>0:
            feasible=False
            break
        planned.append((seq,pid,qty,up,used,serials))
    if not feasible:
        INV.clear(); INV.update(inv_snapshot)
        SERIALS.clear(); SERIALS.extend(serials_snapshot)
        w(f"DELETE FROM order_status_history WHERE order_id={oid} AND from_status='APPROVED' AND to_status='COMPLETED';")
        w(f"UPDATE orders SET status='APPROVED', completed_at=NULL WHERE id={oid};")
        continue
    code=docno_s("GI",ship_date)
    # build surgery info for realism
    w(f"INSERT INTO sales_outs (id,tenant_id,code,dealer_id,terminal_id,business_type,sales_date,status,amount_incl_tax,warehouse_id,remark,approved_at,approved_by,shipped_at,completed_at,created_at,updated_at,created_by,version,is_red,auto_created,source_order_id,source_po_id,extra) "
      f"VALUES ({sout_id},tid,{q(code)},{dealer_id},{hosp},'SALES',DATE {q(ship_date.isoformat())},'COMPLETED',"
      f"(SELECT final_amount FROM orders WHERE id={oid}),{wh},'医院订单配送出库',"
      f"TIMESTAMP {q(ship_d.isoformat()+'+08')},admin_id,TIMESTAMP {q(ship_d.isoformat()+'+08')},TIMESTAMP {q(ship_d.isoformat()+'+08')},now(),now(),admin_id,0,false,true,{oid},NULL,'{{}}'::jsonb);")
    w(f"INSERT INTO sales_out_batches (id,tenant_id,sales_out_id,code,seq,status,remark,confirmed_at,confirmed_by,created_at,updated_at,created_by) "
      f"VALUES ({soutb_id},tid,{sout_id},CONCAT('GIB-',{sout_id},'-01'),1,'CONFIRMED','批次出库',TIMESTAMP {q(ship_d.isoformat()+'+08')},admin_id,now(),now(),admin_id);")
    for seq,pid,qty,up,used,serials in planned:
        # batch/serial info: use first batch
        if used:
            batch=used[0][0]; prod_d=used[0][1]; exp_d=used[0][2]
        else:
            batch=serials[0][1]; prod_d=serials[0][2]; exp_d=serials[0][3]
        qty=sum(u[3] for u in used)+len(serials)
        sn_text=",".join(s[0] for s in serials) if serials else None
        subtotal=round(up*qty,2)
        ext2=round(subtotal/1.13,2); tax2=round(subtotal-ext2,2)
        line_sn = sn_text if (sn_text and len(sn_text) <= 60) else None
        w(f"INSERT INTO sales_out_lines (id,sales_out_id,warehouse_id,product_id,batch_no,serial_no,qty,shipped_qty,cancelled_qty,expected_qty,unit_price,tax_rate,subtotal,seq,quantity,source_order_line_id,returned_qty,return_locked_qty,amount_excl_tax,tax_amount,final_amount,created_at) "
          f"VALUES ({soutl_id},{sout_id},{wh},{pid},{q(batch)},{q(line_sn)},{qty},{qty},0,{qty},{up},{PROD[pid]['tax']},{subtotal},{seq},{qty},(SELECT id FROM order_lines WHERE order_id={oid} AND product_id={pid} LIMIT 1),0,0,{ext2},{tax2},{subtotal},now());")
        w(f"INSERT INTO sales_out_batch_lines (id,batch_id,expected_line_id,expected_line_seq,ship_line_no,product_id,warehouse_id,qty,batch_no,serial_no,unit_price,remark,created_at) "
          f"VALUES ({soutbl_id},{soutb_id},{soutl_id},{seq},{seq},{pid},{wh},{qty},{q(batch)},{q(sn_text)},{up},'销售出库批次',now());")
        w(f"INSERT INTO sales_out_execution_lines (id,tenant_id,sales_out_id,sales_out_line_id,product_id,batch_no,serial_no,qty,seq_no,operator_id,created_at) "
          f"VALUES ({soute_id},tid,{sout_id},{soutl_id},{pid},{q(batch)},{q(sn_text)},{qty},{seq},admin_id,now());")
        # inventory transaction out
        w(f"INSERT INTO inventory_transactions (id,tenant_id,dealer_id,warehouse_id,product_id,batch_no,qty_change,txn_type,ref_doc_type,ref_doc_id,at_time,operator_id,source_line_id) "
          f"VALUES ({itxn_id},tid,{dealer_id},{wh},{pid},{q(batch)},{-qty},'SALES_OUT','SALES_OUT',{sout_id},TIMESTAMP {q(ship_d.isoformat()+'+08')},admin_id,{soutl_id});")
        itxn_id+=1
        # sales out fact (analytics)
        region_subq="(SELECT r.parent_id FROM regions r JOIN dealers dd ON dd.region_id=r.id WHERE dd.id="+str(dealer_id)+")"
        w(f"INSERT INTO sales_out_facts (id,tenant_id,dealer_id,product_id,terminal_id,region_id,sales_date,qty,amount,created_at) "
          f"VALUES ({soutfact_id},tid,{dealer_id},{pid},{hosp},{region_subq},DATE {q(ship_date.isoformat())},{qty},{subtotal},now());")
        soutfact_id+=1
        soutl_id+=1; soutbl_id+=1; soute_id+=1
    soutb_id+=1
    # update order ref
    w(f"UPDATE orders SET ref_sales_out_id={sout_id}, updated_at=now() WHERE id={oid};")
    sout_id+=1

print("SO generated:",so_id-1,"sales outs:",sout_id-1,"remaining INV rows:",len(INV),"remaining serials:",len(SERIALS))


w("")
w("-- ========== INVENTORY BALANCES ==========")
# Write all remaining batch-managed inventory balances
for (dealer,wh,pid,batch,status,prod_d,exp_d),qty in sorted(INV.items()):
    if qty<=0: continue
    w(f"INSERT INTO inventory (id,tenant_id,dealer_id,warehouse_id,product_id,batch_no,prod_date,exp_date,qty,in_source,stock_status,created_at,updated_at,version) "
      f"VALUES ({inv_id},tid,{dealer},{wh},{pid},{q(batch)},DATE {q(prod_d.isoformat())},DATE {q(exp_d.isoformat())},{qty},'PURCHASE','QUALIFIED',now(),now(),0);")
    inv_id+=1
# remaining serial-managed inventory -> inventory rows with serial_no and stock_serials rows
for (sn,dealer,wh,pid,batch,status,prod_d,exp_d) in SERIALS:
    w(f"INSERT INTO inventory (id,tenant_id,dealer_id,warehouse_id,product_id,batch_no,serial_no,prod_date,exp_date,qty,in_source,stock_status,created_at,updated_at,version) "
      f"VALUES ({inv_id},tid,{dealer},{wh},{pid},{q(batch)},{q(sn)},DATE {q(prod_d.isoformat())},DATE {q(exp_d.isoformat())},1,'PURCHASE','QUALIFIED',now(),now(),0);")
    w(f"INSERT INTO stock_serials (id,tenant_id,warehouse_id,product_id,batch_no,serial_no,stock_status,source_doc_type,source_doc_id,received_at,updated_at) "
      f"VALUES ({serial_db_id},tid,{wh},{pid},{q(batch)},{q(sn)},'QUALIFIED','RECEIPT',NULL,TIMESTAMP {q(prod_d.isoformat()+' 11:30:00+08')},now());")
    inv_id+=1; serial_db_id+=1

w("")
w("-- ========== STOCK MOVES (dealer -> hospital consignment, and inter-warehouse) ==========")
sm_id=1; sml_id=1; sm_counters={}
def docno_m(prefix,d):
    ym=d.strftime("%Y%m"); sm_counters[(prefix,ym)]=sm_counters.get((prefix,ym),0)+1
    return f"{prefix}-{ym}-{sm_counters[(prefix,ym)]:04d}"
# simulate ~30 moves from dealer main wh to hospital consignment wh for items still in stock
move_items=[(k,v) for k,v in INV.items() if v>0]
random.shuffle(move_items)
for (dealer,wh,pid,batch,status,prod_d,exp_d),qty in move_items[:30]:
    # find a hospital served by this dealer
    hosps=dealer_hospitals.get(dealer,[1])
    hosp=random.choice(hosps)
    hosp_wh=12+hosp
    if hosp_wh>22: continue
    mqty=min(qty, random.choice([1,2,3,5]))
    if mqty<=0: continue
    mdate=dt.date(2026,8,random.randint(1,18))
    code=docno_m("MV",mdate)
    w(f"INSERT INTO stock_moves (id,tenant_id,code,dealer_id,src_warehouse_id,dst_warehouse_id,status,reason,operator_id,at_time,created_at,updated_at,move_type,from_stock_status,to_stock_status) "
      f"VALUES ({sm_id},tid,{q(code)},{dealer},{wh},{hosp_wh},'COMPLETED','医院寄售库补货',admin_id,TIMESTAMP {q(mdate.isoformat()+' 10:00:00+08')},now(),now(),'HOSPITAL_CONSIGN','QUALIFIED','QUALIFIED');")
    w(f"INSERT INTO stock_move_lines (id,move_id,product_id,batch_no,qty,created_at,from_stock_status,to_stock_status) "
      f"VALUES ({sml_id},{sm_id},{pid},{q(batch)},{mqty},now(),'QUALIFIED','QUALIFIED');")
    w(f"INSERT INTO inventory_transactions (id,tenant_id,dealer_id,warehouse_id,product_id,batch_no,qty_change,txn_type,ref_doc_type,ref_doc_id,at_time,operator_id) "
      f"VALUES ({itxn_id},tid,{dealer},{wh},{pid},{q(batch)},{-mqty},'MOVE_OUT','STOCK_MOVE',{sm_id},TIMESTAMP {q(mdate.isoformat()+' 10:00:00+08')},admin_id);")
    itxn_id+=1
    w(f"INSERT INTO inventory_transactions (id,tenant_id,dealer_id,warehouse_id,product_id,batch_no,qty_change,txn_type,ref_doc_type,ref_doc_id,at_time,operator_id) "
      f"VALUES ({itxn_id},tid,{dealer},{hosp_wh},{pid},{q(batch)},{mqty},'MOVE_IN','STOCK_MOVE',{sm_id},TIMESTAMP {q(mdate.isoformat()+' 10:00:00+08')},admin_id);")
    itxn_id+=1
    # reflect in INV: move to hospital wh
    INV[(dealer,wh,pid,batch,status,prod_d,exp_d)]-=mqty
    nk=(dealer,hosp_wh,pid,batch,status,prod_d,exp_d)
    INV[nk]=INV.get(nk,0)+mqty
    sm_id+=1; sml_id+=1

w("")
w("-- ========== STOCKTAKES (monthly for July & Aug, per dealer main warehouse) ==========")
st_id=1; stl_id=1
for dealer_id in [1,2,3,7,8]:
    wh=dealer_id
    for ym in ["202607","202608"]:
        period=f"{ym[:4]}-{ym[4:]}"
        upload=dt.date(int(ym[:4]),int(ym[4:]),28)
        items=[(k,v) for k,v in INV.items() if k[0]==dealer_id and k[1]==wh and v>0]
        if not items: continue
        diff_total=0
        w(f"INSERT INTO stocktakes (id,tenant_id,dealer_id,period_yyyymm,uploaded_at,uploaded_by,is_late,diff_summary,created_at,updated_at,version) "
          f"VALUES ({st_id},tid,{dealer_id},{q(ym)},TIMESTAMP {q(upload.isoformat()+' 15:00:00+08')},admin_id,false,'{{}}'::jsonb,now(),now(),0);")
        for (d,w2,pid,batch,status,prod_d,exp_d),qty in items[:8]:
            # small variance for some
            diff=random.choice([0,0,0,0,1,-1])
            actual=qty+diff
            diff_total+=diff
            w(f"INSERT INTO stocktake_lines (id,stocktake_id,product_id,batch_no,book_qty,actual_qty,diff_qty,created_at) "
              f"VALUES ({stl_id},{st_id},{pid},{q(batch)},{qty},{actual},{diff},now());")
            stl_id+=1
        w(f"UPDATE stocktakes SET diff_summary=jsonb_build_object('total_diff',{diff_total},'line_count',(SELECT COUNT(*) FROM stocktake_lines WHERE stocktake_id={st_id})) WHERE id={st_id};")
        st_id+=1

print("inventory rows written, moves:",sm_id-1,"stocktakes:",st_id-1)


w("")
w("-- ========== SURGERY REPORTS ==========")
srg_id=1; srgl_id=1
# surgery reports derived from recent sales outs (use July-Aug completed sales-out facts)
surgery_types=["股骨近端骨折内固定术","胫骨平台骨折内固定术","腰椎椎体间融合术","胸腰椎骨折复位内固定术","全髋关节置换术","全膝关节置换术","前交叉韧带重建术","肩袖损伤修复术"]
doctors=["王大伟主任医师","李建华副主任医师","陈志明主治医师","张磊主任医师","刘洋副主任医师","赵海涛主任医师"]
patients=["张某(男,58岁)","李某(女,64岁)","王某(男,45岁)","陈某(女,72岁)","刘某(男,38岁)","赵某(女,55岁)","黄某(男,67岁)","周某(女,49岁)"]
for idx in range(40):
    d=dt.date(2026,7,1)+dt.timedelta(days=random.randint(0,49))
    dealer_id=random.choice([1,2,3,7,8,9])
    hosp=random.choice(dealer_hospitals.get(dealer_id,[1]))
    hosp_wh=12+hosp
    # 1-3 product lines, prefer implant items (serial or high value)
    nlines=random.choice([1,2,3])
    chosen=random.sample([1,2,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21],nlines)
    code=f"SR-{d.strftime('%Y%m')}-{srg_id:04d}"
    sales_user=random.choice([14,15,16,18,22,26])
    doctor=random.choice(doctors); patient=random.choice(patients)
    w(f"INSERT INTO surgery_reports (id,tenant_id,code,dealer_id,terminal_id,warehouse_id,sales_user_id,surgery_date,patient_info,doctor_name,status,remark,created_at,updated_at,created_by) "
      f"VALUES ({srg_id},tid,{q(code)},{dealer_id},{hosp},{hosp_wh if hosp_wh<=22 else dealer_id},{sales_user},DATE {q(d.isoformat())},{q(patient)},{q(doctor)},'COMPLETED','术后植入物使用登记，跟台完成',now(),now(),admin_id);")
    for seq,pid in enumerate(chosen,1):
        qty=random.choice([1,1,2])
        up=PROD[pid]["price"]
        batch=f"B{d.strftime('%y%m%d')}{pid:03d}R"
        sn=None
        if PROD[pid]["serial"]:
            sn=f"SN{PROD[pid]['code'].replace('PRD-','')}-USE-{srg_id:04d}-{seq}"
        w(f"INSERT INTO surgery_report_lines (id,report_id,product_id,qty,batch_no,serial_no,unit_price,remark,created_at) "
          f"VALUES ({srgl_id},{srg_id},{pid},{qty},{q(batch)},{q(sn)},{up},(SELECT name_cn FROM products WHERE id={pid}),now());")
        srgl_id+=1
    srg_id+=1

w("")
w("-- ========== CONTRACTS ==========")
ct_id=1
categories=[("DISTRIBUTION","年度经销协议",1800000),("SUPPLY","供货框架合同",1200000),("AUTHORIZATION","授权委托书",900000),("PROMOTION","市场推广协议",450000),("SERVICE","售后服务协议",360000)]
for dealer_id in range(1,13):
    for ci,(cat,cname,base) in enumerate(categories,1):
        # only create some contracts per dealer (3 of 5)
        if random.random()<0.4: continue
        sign=dt.date(2026,1,random.randint(5,25))
        valid_from=dt.date(2026,1,1)
        valid_to=dt.date(2026,12,31)
        code=f"CT-2026-{ct_id:04d}"
        target=round(base+ct_id*9800,2)
        signed=round(target*random.choice([0.82,0.88,0.95,1.02]),2)
        owner=random.choice(["区域经理-周航","区域经理-陈晨","区域经理-李娜","区域经理-王强"])
        w(f"INSERT INTO contracts (id,tenant_id,code,name,category,application_type,dealer_id,vendor_party,dealer_party,sign_city,valid_from,valid_to,target_amount,signed_amount,payment_terms,settlement_cycle,owner_name,owner_phone,form_data,status,submitted_at,effective_at,created_by,updated_by,created_at,updated_at,version,template_version) "
          f"VALUES ({ct_id},tid,{q(code)},CONCAT({q(cname)},'-',(SELECT name FROM dealers WHERE id={dealer_id})),{q(cat)},'NEW',{dealer_id},'上海鼎医智能科技有限公司',(SELECT name FROM dealers WHERE id={dealer_id}),(SELECT city FROM dealer_addresses WHERE dealer_id={dealer_id} AND is_default=true LIMIT 1),"
          f"DATE {q(valid_from.isoformat())},DATE {q(valid_to.isoformat())},{target},{signed},'月结60天，凭签收单及增值税专用发票付款',CASE WHEN {q(cat)}='PROMOTION' THEN '季度结算' ELSE '月度对账' END,"
          f"{q(owner)},'1381888{ct_id%10000:04d}','{{}}'::jsonb,'effective',TIMESTAMP {q(sign.isoformat()+' 10:00:00+08')},TIMESTAMP {q(valid_from.isoformat()+' 00:00:00+08')},admin_id,admin_id,now(),now(),0,1);")
        ct_id+=1

w("")
w("-- ========== AUTHORIZATIONS (derived from contracts) ==========")
au_id=1
for dealer_id in range(1,13):
    # each dealer gets 1-3 product-line authorizations
    pls=random.sample([1,2,3,4,5],random.choice([1,2,3]))
    for pl in pls:
        # find a relevant contract
        valid_from=dt.date(2026,1,1); valid_to=dt.date(2026,12,31)
        w(f"INSERT INTO authorizations (id,tenant_id,dealer_id,contract_id,auth_type,product_line_id,valid_from,valid_to,status,source,remark,created_at,updated_at,version) "
          f"VALUES ({au_id},tid,{dealer_id},(SELECT id FROM contracts WHERE dealer_id={dealer_id} AND category='DISTRIBUTION' LIMIT 1),'PRODUCT_LINE',{pl},DATE {q(valid_from.isoformat())},DATE {q(valid_to.isoformat())},'active','contract',(SELECT name FROM product_lines WHERE id={pl})||'产品线授权',now(),now(),0);")
        au_id+=1
    # some hospital-specific (terminal) authorizations
    for hosp in dealer_hospitals.get(dealer_id,[])[:1]:
        w(f"INSERT INTO authorizations (id,tenant_id,dealer_id,contract_id,auth_type,product_line_id,terminal_id,valid_from,valid_to,status,source,remark,created_at,updated_at,version) "
          f"VALUES ({au_id},tid,{dealer_id},(SELECT id FROM contracts WHERE dealer_id={dealer_id} LIMIT 1),'TERMINAL',{random.choice([1,2,3])},{hosp},DATE '2026-01-01',DATE '2026-12-31','active','contract','终端医院销售授权',now(),now(),0);")
        au_id+=1

print("surgery reports:",srg_id-1,"contracts:",ct_id-1,"authorizations:",au_id-1)


w("")
w("-- ========== PROMOTIONS ==========")
prom_id=1; promr_id=1
promos=[
 ("PROMO-2026-Q3-TRAUMA","2026年三季度创伤内固定满十减五百","FULL_REDUCTION",10,500),
 ("PROMO-2026-Q3-MOQ","关节假体满十享九三折","FULL_REDUCTION",10,0.07),
 ("PROMO-2026-Q3-GIFT","脊柱融合器买十赠一","GIFT",10,1),
]
for code,name,ptype,p1,p2 in promos:
    w(f"INSERT INTO promotions (id,tenant_id,code,name,promo_type,priority,valid_from,valid_to,dealer_scope,product_scope,exclusive,status,description,created_by,approved_by,approved_at,created_at,updated_at,version) "
      f"VALUES ({prom_id},tid,{q(code)},{q(name)},{q(ptype)},50,TIMESTAMP '2026-07-01 00:00:00+08',TIMESTAMP '2026-09-30 23:59:59+08','{{\"type\":\"ALL\"}}'::jsonb,'{{\"type\":\"ALL\"}}'::jsonb,false,'active','季度促销活动',admin_id,admin_id,TIMESTAMP '2026-06-25 10:00:00+08',now(),now(),0);")
    line_id_for = {"PROMO-2026-Q3-TRAUMA":1, "PROMO-2026-Q3-MOQ":3, "PROMO-2026-Q3-GIFT":2}
    target_line = line_id_for.get(code)
    scope = (',"targetProductLineId":'+str(target_line)) if target_line else ''
    if ptype=="FULL_REDUCTION":
        if p2 < 1:
            detail_str='{"buyQty":'+str(p1)+',"discountType":"RATE","reduceAmount":'+str(p2)+scope+'}'
        else:
            detail_str='{"buyQty":'+str(p1)+',"reduceAmount":'+str(p2)+scope+'}'
    elif ptype=="MOQ":
        detail_str='{"buyQty":'+str(p1)+',"discountType":"RATE","reduceAmount":'+str(p2)+scope+'}'
    else:
        detail_str='{"buyQty":'+str(p1)+',"giftQty":'+str(p2)+',"giftProductId":7,"cycle":"EVERY_N"'+scope+'}'
    w(f"INSERT INTO promotion_rules (id,promotion_id,seq,rule_detail,created_at,updated_at) "
      f"VALUES ({promr_id},{prom_id},1,'{detail_str}'::jsonb,now(),now());")
    w(f"INSERT INTO promotion_status_logs (id,promotion_id,from_status,to_status,operator_id,comment,at_time) "
      f"VALUES ({promr_id},{prom_id},'draft','approved',admin_id,'审批通过',now());")
    prom_id+=1; promr_id+=1

w("")
w("-- ========== REBATE PREVIEWS & SETTLEMENTS (Jan-Aug 2026 per active dealer) ==========")
rp_id=1; rs_id=1
for dealer_id in range(1,13):
    level=("T1","T1","T1","T2","T2","T2","T1","T1","T2","T2","T3","T3")[dealer_id-1]
    base={"T1":900000,"T2":520000,"T3":280000}[level]
    for m in range(1,9):
        ym=f"2026{m:02d}"
        target=round(base+dealer_id*17000+m*18000,2)
        # actual around 0.7-1.25 of target
        factor=0.70+((dealer_id*7+m*13)%55)/100.0
        actual=round(target*factor,2)
        rate=round(actual/target,4)
        tier="T3" if rate>=1.2 else ("T2" if rate>=1 else ("T1" if rate>=0.9 else "T0"))
        gross=round(actual*(0.058 if rate>=1.2 else 0.045 if rate>=1 else 0.032 if rate>=0.9 else 0.018),2)
        ded=round(gross*random.choice([0.02,0.03,0.05,0.08]),2)
        net=round(gross-ded,2)
        reason=random.choice(["返利扣减","价保扣减","窜货扣减","促销补差"])
        tier_json = '{\"tier\":\"' + tier + '\",\"rate\":' + str(rate) + '}'
        ded_json = '{\"reason\":\"' + reason + '\",\"amount\":' + str(ded) + '}'
        w(f"INSERT INTO rebate_previews (id,tenant_id,dealer_id,period_yyyymm,target_amount,actual_amount,achievement_rate,tier_hit,gross_rebate,deductions,net_rebate,snapshot_at,created_at,updated_at,version) "
          f"VALUES ({rp_id},tid,{dealer_id},{q(ym)},{target},{actual},{rate},'{tier_json}'::jsonb,{gross},'{ded_json}'::jsonb,{net},now(),now(),now(),0);")
        rp_id+=1
    # one settlement for July (closed)
    ym="202607"
    w(f"INSERT INTO rebate_settlements (id,tenant_id,dealer_id,period_yyyymm,net_rebate,status,settled_at,paid_at,created_at,updated_at,version) "
      f"VALUES ({rs_id},tid,{dealer_id},{q(ym)},(SELECT net_rebate FROM rebate_previews WHERE dealer_id={dealer_id} AND period_yyyymm={q(ym)}),'PAID',TIMESTAMP '2026-08-05 10:00:00+08',TIMESTAMP '2026-08-10 14:00:00+08',now(),now(),0);")
    rs_id+=1

w("")
w("-- ========== RMA AUTHORIZATIONS + ORDERS (returns) ==========")
rmaa_id=1; rmao_id=1
for dealer_id in [1,2,3,7,8]:
    w(f"INSERT INTO rma_authorizations (id,tenant_id,code,dealer_id,product_line_id,quota_amount,quota_used,valid_from,valid_to,status,reason,created_by,created_at,updated_at,version) "
      f"VALUES ({rmaa_id},tid,CONCAT('RMA-A-',LPAD({rmaa_id}::text,4,'0')),{dealer_id},{random.choice([1,2,3,4])},50000,{random.choice([5000,12000,23000])},DATE '2026-01-01',DATE '2026-12-31','active','年度质量问题退货授权',admin_id,now(),now(),0);")
    # 1-2 rma orders
    for _ in range(random.choice([1,2])):
        code=f"RMA-2026-{rmao_id:04d}"
        amount=round(random.choice([3000,8000,15000,25000]),2)
        rtype=random.choice(["QUALITY","EXPIRED","DAMAGED"])
        rma_pid=random.randint(1,24); rma_qty=random.choice([1,2,3]); rma_reason=random.choice(["包装破损","近效期","规格不符"])
        lines_json = '[{\"productId\":' + str(rma_pid) + ',\"qty\":' + str(rma_qty) + ',\"reason\":\"' + rma_reason + '\"}]'
        w(f"INSERT INTO rma_orders (id,tenant_id,code,ref_rma_auth_id,dealer_id,rma_type,amount,status,lines,reason,submitted_at,completed_at,created_at,updated_at,created_by,version) "
          f"VALUES ({rmao_id},tid,{q(code)},{rmaa_id},{dealer_id},{q(rtype)},{amount},'COMPLETED','{lines_json}'::jsonb,'售后退货处理',TIMESTAMP '2026-07-15 10:00:00+08',TIMESTAMP '2026-07-20 15:00:00+08',now(),now(),admin_id,0);")
        rmao_id+=1
    rmaa_id+=1

w("")
w("-- ========== INVENTORY ADJUSTMENTS (small sample) ==========")
iadj_id=1; iadjl_id=1
for dealer_id in [1,2,7]:
    wh=dealer_id
    code=f"ADJ-202608-{iadj_id:03d}"
    w(f"INSERT INTO inventory_adjustments (id,tenant_id,code,dealer_id,warehouse_id,adj_category,adj_type,status,reason,operator_id,approver_id,created_at,updated_at,version) "
      f"VALUES ({iadj_id},tid,{q(code)},{dealer_id},{wh},'STOCK','INVENTORY_COUNT','APPROVED','月度盘点报溢报损调整',admin_id,admin_id,now(),now(),0);")
    for pid in random.sample(range(1,25),3):
        qty=random.choice([1,-1,2,-2])
        w(f"INSERT INTO adjustment_lines (id,adjustment_id,product_id,batch_no,qty,reason,created_at) "
          f"VALUES ({iadjl_id},{iadj_id},{pid},CONCAT('BADJ',LPAD({pid}::text,3,'0')),{qty},'盘点差异调整',now());")
        iadjl_id+=1
    iadj_id+=1

w("")
w("-- ========== DEALER KPI SNAPSHOTS (Jul/Aug) ==========")
kpi_id=1
for dealer_id in range(1,13):
    for ym in ["202607","202608"]:
        w(f"INSERT INTO dealer_kpi_snapshots (id,tenant_id,dealer_id,period_yyyymm,stock_report_rate,sales_report_rate,order_pass_rate,return_rate,created_at,updated_at) "
          f"VALUES ({kpi_id},tid,{dealer_id},{q(ym)},{round(random.random()*0.05+0.95,4)},{round(random.random()*0.06+0.94,4)},{round(random.random()*0.03+0.97,4)},{round(random.random()*0.02,4)},now(),now());")
        kpi_id+=1

w("")
w("-- ========== PURCHASE INVOICES (for completed POs, sample) ==========")
pi_id=1
for idx,(po,dealer,wh,line_rows,pd) in enumerate(po_records[:40]):
    invno=f"PI{pd.strftime('%Y%m')}{idx+1:04d}"
    invd=pd+dt.timedelta(days=4)
    w(f"INSERT INTO purchase_invoices (id,tenant_id,ref_order_id,invoice_no,invoice_date,amount,tax_amount,tax_rate,image_url,uploaded_by,uploaded_at,created_at,updated_at,version) "
      f"VALUES ({pi_id},tid,{po},{q(invno)},DATE {q(invd.isoformat())},(SELECT final_amount FROM purchase_orders WHERE id={po}),(SELECT tax_amount FROM purchase_orders WHERE id={po}),0.13,NULL,admin_id,now(),now(),now(),0);")
    pi_id+=1

w("")
w("-- ========== SALES INVOICES (for completed sales outs, sample) ==========")
si_id=1
completed_outs=[o for o in sales_orders if o[7]=="COMPLETED"]
for idx,row in enumerate(completed_outs[:40]):
    oid=row[0]; sd=row[9] or row[6]
    invno=f"SI{sd.strftime('%Y%m') if sd else '202608'}{idx+1:04d}"
    invd=(sd or dt.datetime(2026,8,1))+dt.timedelta(days=2)
    if isinstance(invd,dt.datetime): invd=invd.date()
    w(f"INSERT INTO sales_invoices (id,tenant_id,ref_sales_out_id,invoice_no,invoice_date,amount,tax_amount,image_url,uploaded_at,uploaded_by,created_at,updated_at,version) "
      f"VALUES ({si_id},tid,(SELECT id FROM sales_outs WHERE source_order_id={oid} LIMIT 1),{q(invno)},DATE {q(invd.isoformat())},(SELECT final_amount FROM orders WHERE id={oid}),(SELECT tax_amount FROM orders WHERE id={oid}),NULL,now(),admin_id,now(),now(),0);")
    si_id+=1

w("")
w("-- ========== DOC NO SEQUENCES (align to generated volumes) ==========")
w("DELETE FROM doc_no_sequences WHERE tenant_id=tid;")
for prefix in ["PO","GR","SO","GI","CT","MV","RP","RS","GIR"]:
    for m in range(6,9):
        ym=f"2026{m:02d}"
        # estimate counts
        cnt={"PO":20,"GR":20,"SO":50,"GI":40,"CT":15,"MV":10,"RP":12,"RS":8,"GIR":6}.get(prefix,10)
        w(f"INSERT INTO doc_no_sequences (tenant_id,prefix,date_key,last_seq) VALUES (tid,{q(prefix)},{q(ym)},{cnt});")

w("")
w("")
w("-- Reset all sequences to max(id)+1 after explicit-id inserts")
w("DO $reset$ DECLARE r record; mx bigint; BEGIN")
w("  FOR r IN SELECT table_name, column_name, pg_get_serial_sequence(format('%I', table_name), column_name) AS seq")
w("           FROM information_schema.columns WHERE table_schema='public' AND column_default LIKE 'nextval%' AND is_identity='NO'")
w("  LOOP")
w("    EXECUTE format('SELECT COALESCE(max(%I),0) FROM %I', r.column_name, r.table_name) INTO mx;")
w("    IF mx > 0 THEN EXECUTE format('SELECT setval(%L, %s, true)', r.seq, mx); END IF;")
w("  END LOOP;")
w("END $reset$;")
w("")
w("RAISE NOTICE 'ALL DATA SEED DONE';")
w("END $$;")
w("COMMIT;")
w("")
w("-- VACUUM ANALYZE to refresh planner stats after bulk reset")
w("VACUUM ANALYZE;")

with open(OUT,"w",encoding="utf-8") as f:
    f.write("\n".join(L)+"\n")
print("FINAL lines:",len(L))
print("wrote",OUT)

