# -*- coding: utf-8 -*-
"""校验源代码 docx 的关键指标：
- 总页数（通过分页符统计 + 1）
- 每页实际非空行数
- 是否含敏感词（copyright/license/@author ai/generated 等）
- 是否含中文字符占比
"""
import re
from docx import Document

p = r"d:\Workspace\TRAE\DMS\软著申请材料\02_源代码\源程序_DMS经销商管理系统V1.0_前30页后30页.docx"
doc = Document(p)

paras = doc.paragraphs
print("总段落数（含空行）:", len(paras))

# 统计每个分页符之间的行数
pages = []
current = []
for para in paras:
    # 检测分页符
    has_break = False
    for run in para.runs:
        for br in run._r.findall('.//{http://schemas.openxmlformats.org/wordprocessingml/2006/main}br'):
            if br.get('{http://schemas.openxmlformats.org/wordprocessingml/2006/main}type') == 'page':
                has_break = True
    current.append(para.text)
    if has_break:
        pages.append(current)
        current = []
if current:
    pages.append(current)

print(f"页数（分页符+1）: {len(pages)}")
for i, pg in enumerate(pages[:3] + pages[-3:], 1):
    idx = i if i <= 3 else len(pages) - 3 + i - 3
    non_blank = sum(1 for x in pg if x.strip())
    print(f"  Page {idx}: total lines={len(pg)}, non-blank={non_blank}")

# 敏感词检查
text = "\n".join(p.text for p in paras)
sensitive = ["copyright", "license", "@author", "generated by", "do not copy",
             "apache", "gnu general public", "mozilla public license",
             "mit license", "lgpl", "gpl", "copilot", "chatgpt", "claude",
             "trae", "cursor ai", "本文件由", "ai生成", "ai 生成", "@date"]
hits = []
for w in sensitive:
    for m in re.finditer(re.escape(w), text, re.IGNORECASE):
        start = max(0, m.start() - 30); end = min(len(text), m.end() + 30)
        hits.append((w, text[start:end].replace("\n", " | ")))
print(f"\n敏感词命中 {len(hits)} 条:")
for w, ctx in hits[:30]:
    print(f"  [{w}] ...{ctx}...")

# 中文字符比例（代码中中文主要是注释/字符串）
zh = sum(1 for c in text if '\u4e00' <= c <= '\u9fff')
print(f"\n中文字符数: {zh} / 总字符数 {len(text)} ({zh*100//max(1,len(text))}%)")
