import paramiko, sys, time
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
c=paramiko.SSHClient(); c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('8.133.193.238', username='root', password='Welcomeyyx0616', timeout=15, allow_agent=False, look_for_keys=False)
def run(cmd, timeout=120):
 print('\n>>>',cmd[:260])
 si,so,se=c.exec_command(cmd,timeout=timeout)
 print(so.read().decode('utf-8','replace').rstrip())
 err=se.read().decode('utf-8','replace').rstrip()
 if err: print('STDERR:',err[:4000])
run('docker rm -f dms-v55-debug 2>/dev/null || true')
run('docker run -d --name dms-v55-debug --network dms-net -e DB_HOST=dms-postgres -e DB_NAME=dms_flyway_preview -e DB_USERNAME=dms -e DB_USER=dms -e DB_PASSWORD=dms123456 -e REDIS_HOST=dms-redis -e MINIO_ENDPOINT=http://dms-minio:9000 -e MINIO_ACCESS_KEY=minioadmin -e MINIO_SECRET_KEY=minioadmin -e SPRING_FLYWAY_ENABLED=false --entrypoint sleep dms-backend:latest 3600')
time.sleep(2)
run("docker exec dms-v55-debug sh -c \"unzip -p app.jar BOOT-INF/classes/db/migration/V55__realistic_demo_profile_data.sql > /tmp/V55.sql && sed -n '1,20p' /tmp/V55.sql\"")
run("docker exec dms-v55-debug sh -c \"PGPASSWORD=dms123456 psql -h dms-postgres -U dms -d dms_flyway_preview -v ON_ERROR_STOP=1 -f /tmp/V55.sql\"", timeout=180)
c.close()
