import paramiko, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
c=paramiko.SSHClient(); c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('8.133.193.238', username='root', password='Welcomeyyx0616', timeout=15, allow_agent=False, look_for_keys=False)
def run(cmd, timeout=120):
 print('\n>>>',cmd[:260])
 si,so,se=c.exec_command(cmd,timeout=timeout)
 print(so.read().decode('utf-8','replace').rstrip())
 err=se.read().decode('utf-8','replace').rstrip()
 if err: print('STDERR:',err[:4000])
run('docker cp dms-frontend-vue:/etc/nginx/nginx.conf /opt/dms/frontend-vue/nginx-vue.prod-before-auth-fix.conf')
run("python3 - <<'PY'\nfrom pathlib import Path\np=Path('/opt/dms/frontend-vue/nginx-vue.conf')\ns=p.read_text()\ns=s.replace('''    location /api/auth/ {\\n      rewrite ^/api/auth/(.*)$ /auth/$1 break;\\n      proxy_pass http://dms-backend:8080;\\n      proxy_set_header Host $host;\\n      proxy_set_header X-Real-IP $remote_addr;\\n      proxy_set_header Authorization $http_authorization;\\n    }''','''    location /api/auth/ {\\n      proxy_pass http://dms-backend:8080;\\n      proxy_set_header Host $host;\\n      proxy_set_header X-Real-IP $remote_addr;\\n      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\\n      proxy_set_header Authorization $http_authorization;\\n      proxy_read_timeout 300s;\\n    }''')\np.write_text(s)\nprint('updated nginx-vue.conf')\nPY")
run('grep -n -A8 "location /api/auth" /opt/dms/frontend-vue/nginx-vue.conf')
run('cd /opt/dms/frontend-vue && docker build -f Dockerfile.dist -t dms-frontend-vue:latest .', timeout=300)
run('docker rm -f dms-frontend-vue')
run('docker run -d --name dms-frontend-vue --restart unless-stopped -p 8081:80 --network dms-net dms-frontend-vue:latest')
run('sleep 2; curl -i -s -m 10 -X POST -H "Content-Type: application/json" -d \'{"tenantCode":"default","username":"admin","password":"Sh123456"}\' http://127.0.0.1:8081/api/auth/login | head -20')
run('curl -s -o /dev/null -w "home=%{http_code}\\n" http://127.0.0.1:8081/')
run('curl -s -o /dev/null -w "admin=%{http_code}\\n" http://127.0.0.1:8081/admin/')
c.close()
