import paramiko
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('8.133.193.238', port=22, username='root', password='Welcomeyyx0616', timeout=10, allow_agent=False, look_for_keys=False)
si, so, se = c.exec_command('docker ps --format "{{.Names}} {{.Status}}"', timeout=10)
out = so.read().decode('utf-8', errors='replace')
err = se.read().decode('utf-8', errors='replace')
print('STDOUT:', out)
print('STDERR:', err)
c.close()
